Quantum Exact Simulation Toolkit: Catch::Generators::ChunkGenerator< T > Class Template Reference
Catch::Generators::ChunkGenerator< T > Class Template Reference final abstract
#include <catch.hpp>
Public Types
using type = std::vector< T >
Public Member Functions
ChunkGenerator (size_t size, GeneratorWrapper< T > generator)
std::vector< T > const & get () const override
virtual std::vector< T > const & get () const=0
bool next () override
Private Attributes
std::vector< T > m_chunk
size_t m_chunk_size
GeneratorWrapper< T > m_generator
bool m_used_up = false
Detailed Description
template<typename T>
class Catch::Generators::ChunkGenerator< T >
Definition at line 4232 of file catch.hpp.
Member Typedef Documentation
type
using Catch::Generators::IGenerator< std::vector< T > >::type = std::vector< T > inherited
Definition at line 3883 of file catch.hpp.
Constructor & Destructor Documentation
ChunkGenerator()
template<typename T > Catch::Generators::ChunkGenerator< T >::ChunkGenerator (size_t size, GeneratorWrapper< T > generator) inline
Definition at line 4238 of file catch.hpp.
                                                                    :
             m_chunk_size(size), m_generator(std::move(generator))
         {
             m_chunk.reserve(m_chunk_size);
             if (m_chunk_size != 0) {
                 m_chunk.push_back(m_generator.get());
                 for (size_t i = 1; i < m_chunk_size; ++i) {
                     if (!m_generator.next()) {
                         Catch::throw_exception(GeneratorException("Not enough values to initialize the first chunk"));
                     }
                     m_chunk.push_back(m_generator.get());
                 }
             }
         }
References Catch::Generators::GeneratorWrapper< T >::get(), Catch::Generators::GeneratorWrapper< T >::next(), and Catch::throw_exception().
Member Function Documentation
get() [1/2]
template<typename T > std::vector<T> const& Catch::Generators::ChunkGenerator< T >::get () const inline override
Definition at line 4252 of file catch.hpp.
{
             return m_chunk;
         }
get() [2/2]
virtual std::vector< T > const& Catch::Generators::IGenerator< std::vector< T > >::get pure virtual inherited
next()
template<typename T > bool Catch::Generators::ChunkGenerator< T >::next () inline override virtual
Implements Catch::Generators::GeneratorUntypedBase.
Definition at line 4255 of file catch.hpp.
{
             m_chunk.clear();
             for (size_t idx = 0; idx < m_chunk_size; ++idx) {
                 if (!m_generator.next()) {
                     return false;
                 }
                 m_chunk.push_back(m_generator.get());
             }
             return true;
         }
References Catch::Generators::GeneratorWrapper< T >::get(), and Catch::Generators::GeneratorWrapper< T >::next().
Field Documentation
m_chunk
template<typename T > std::vector<T> Catch::Generators::ChunkGenerator< T >::m_chunk private
Definition at line 4233 of file catch.hpp.
m_chunk_size
template<typename T > size_t Catch::Generators::ChunkGenerator< T >::m_chunk_size private
Definition at line 4234 of file catch.hpp.
m_generator
template<typename T > GeneratorWrapper<T> Catch::Generators::ChunkGenerator< T >::m_generator private
Definition at line 4235 of file catch.hpp.
m_used_up
template<typename T > bool Catch::Generators::ChunkGenerator< T >::m_used_up = false private
Definition at line 4236 of file catch.hpp.
The documentation for this class was generated from the following file:
catch.hpp