Quantum Exact Simulation Toolkit: Catch::Generators::FilterGenerator< T, Predicate > Class Template Reference
Catch::Generators::FilterGenerator< T, Predicate > Class Template Reference
#include <catch.hpp>
Public Types
using type = T
Public Member Functions
template<typename P = Predicate>
FilterGenerator (P &&pred, GeneratorWrapper< T > &&generator)
T const & get () const override
bool next () override
Private Attributes
GeneratorWrapper< T > m_generator
Predicate m_predicate
Detailed Description
template<typename T, typename Predicate>
class Catch::Generators::FilterGenerator< T, Predicate >
Definition at line 4085 of file catch.hpp.
Member Typedef Documentation
type
template<typename T > using Catch::Generators::IGenerator< T >::type = T inherited
Definition at line 3883 of file catch.hpp.
Constructor & Destructor Documentation
FilterGenerator()
template<typename T , typename Predicate > template<typename P = Predicate> Catch::Generators::FilterGenerator< T, Predicate >::FilterGenerator (P && pred, GeneratorWrapper< T > && generator) inline
Definition at line 4090 of file catch.hpp.
                                                                   :
             m_generator(std::move(generator)),
             m_predicate(std::forward<P>(pred))
         {
             if (!m_predicate(m_generator.get())) {
                 // It might happen that there are no values that pass the
                 // filter. In that case we throw an exception.
                 auto has_initial_value = next();
                 if (!has_initial_value) {
                     Catch::throw_exception(GeneratorException("No valid value found in filtered generator"));
                 }
             }
         }
References Catch::Generators::GeneratorWrapper< T >::get(), and Catch::throw_exception().
Member Function Documentation
get()
template<typename T , typename Predicate > T const& Catch::Generators::FilterGenerator< T, Predicate >::get () const inline override virtual
Implements Catch::Generators::IGenerator< T >.
Definition at line 4104 of file catch.hpp.
{
             return m_generator.get();
         }
References Catch::Generators::GeneratorWrapper< T >::get().
next()
template<typename T , typename Predicate > bool Catch::Generators::FilterGenerator< T, Predicate >::next () inline override virtual
Implements Catch::Generators::GeneratorUntypedBase.
Definition at line 4108 of file catch.hpp.
{
             bool success = m_generator.next();
             if (!success) {
                 return false;
             }
             while (!m_predicate(m_generator.get()) && (success = m_generator.next()) == true);
             return success;
         }
References Catch::Generators::GeneratorWrapper< T >::get(), and Catch::Generators::GeneratorWrapper< T >::next().
Field Documentation
m_generator
template<typename T , typename Predicate > GeneratorWrapper<T> Catch::Generators::FilterGenerator< T, Predicate >::m_generator private
Definition at line 4086 of file catch.hpp.
m_predicate
template<typename T , typename Predicate > Predicate Catch::Generators::FilterGenerator< T, Predicate >::m_predicate private
Definition at line 4087 of file catch.hpp.
The documentation for this class was generated from the following file:
catch.hpp