Quantum Exact Simulation Toolkit: Catch::Generators::GeneratorWrapper< T > Class Template Reference
Catch::Generators::GeneratorWrapper< T > Class Template Reference final
#include <catch.hpp>
Public Member Functions
GeneratorWrapper (std::unique_ptr< IGenerator< T >> generator)
T const & get () const
bool next ()
Private Attributes
std::unique_ptr< IGenerator< T > > m_generator
Detailed Description
template<typename T>
class Catch::Generators::GeneratorWrapper< T >
Definition at line 3921 of file catch.hpp.
Constructor & Destructor Documentation
GeneratorWrapper()
template<typename T > Catch::Generators::GeneratorWrapper< T >::GeneratorWrapper (std::unique_ptr< IGenerator< T >> generator) inline
Definition at line 3924 of file catch.hpp.
                                                                 :
             m_generator(std::move(generator))
         {}
Member Function Documentation
get()
template<typename T > T const& Catch::Generators::GeneratorWrapper< T >::get () const inline
Definition at line 3927 of file catch.hpp.
{
             return m_generator->get();
         }
Referenced by Catch::Generators::ChunkGenerator< T >::ChunkGenerator(), Catch::Generators::FilterGenerator< T, Predicate >::FilterGenerator(), Catch::Generators::TakeGenerator< T >::get(), Catch::Generators::FilterGenerator< T, Predicate >::get(), Catch::Generators::RepeatGenerator< T >::get(), Catch::Generators::FilterGenerator< T, Predicate >::next(), Catch::Generators::MapGenerator< T, U, Func >::next(), and Catch::Generators::ChunkGenerator< T >::next().
next()
template<typename T > bool Catch::Generators::GeneratorWrapper< T >::next () inline
Definition at line 3930 of file catch.hpp.
                     {
             return m_generator->next();
         }
Referenced by Catch::Generators::ChunkGenerator< T >::ChunkGenerator(), Catch::Generators::TakeGenerator< T >::next(), Catch::Generators::FilterGenerator< T, Predicate >::next(), Catch::Generators::RepeatGenerator< T >::next(), Catch::Generators::MapGenerator< T, U, Func >::next(), and Catch::Generators::ChunkGenerator< T >::next().
Field Documentation
m_generator
template<typename T > std::unique_ptr<IGenerator<T> > Catch::Generators::GeneratorWrapper< T >::m_generator private
Definition at line 3922 of file catch.hpp.
The documentation for this class was generated from the following file:
catch.hpp