Quantum Exact Simulation Toolkit: Catch::ExprLhs< LhsT > Class Template Reference
Catch::ExprLhs< LhsT > Class Template Reference
#include <catch.hpp>
Public Member Functions
ExprLhs (LhsT lhs)
auto makeUnaryExpr () const -> UnaryExpr< LhsT >
auto operator!= (bool rhs) -> BinaryExpr< LhsT, bool > const
template<typename RhsT >
auto operator!= (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator&& (RhsT const &) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator< (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator<= (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
auto operator== (bool rhs) -> BinaryExpr< LhsT, bool > const
template<typename RhsT >
auto operator== (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator> (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator>= (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator|| (RhsT const &) -> BinaryExpr< LhsT, RhsT const & > const
Private Attributes
LhsT m_lhs
Detailed Description
template<typename LhsT>
class Catch::ExprLhs< LhsT >
Definition at line 2292 of file catch.hpp.
Constructor & Destructor Documentation
ExprLhs()
template<typename LhsT > Catch::ExprLhs< LhsT >::ExprLhs (LhsT lhs) inline explicit
Definition at line 2295 of file catch.hpp.
 : m_lhs( lhs ) {}
Member Function Documentation
makeUnaryExpr()
template<typename LhsT > auto Catch::ExprLhs< LhsT >::makeUnaryExpr () const -> UnaryExpr<LhsT> inline
Definition at line 2344 of file catch.hpp.
{
             return UnaryExpr<LhsT>{ m_lhs };
         }
References Catch::ExprLhs< LhsT >::m_lhs.
Referenced by Catch::AssertionHandler::handleExpr(), and Catch::handleExpression().
operator!=() [1/2]
template<typename LhsT > auto Catch::ExprLhs< LhsT >::operator!= (bool rhs) -> BinaryExpr<LhsT, bool> const inline
Definition at line 2309 of file catch.hpp.
{
             return { m_lhs != rhs, m_lhs, "!=", rhs };
         }
References Catch::ExprLhs< LhsT >::m_lhs.
operator!=() [2/2]
template<typename LhsT > template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator!= (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 2306 of file catch.hpp.
{
             return { compareNotEqual( m_lhs, rhs ), m_lhs, "!=", rhs };
         }
References Catch::compareNotEqual(), and Catch::ExprLhs< LhsT >::m_lhs.
operator&&()
template<typename LhsT > template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator&& (RhsT const &) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 2331 of file catch.hpp.
{
             static_assert(always_false<RhsT>::value,
             "operator&& is not supported inside assertions, "
             "wrap the expression inside parentheses, or decompose it");
         }
operator<()
template<typename LhsT > template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator< (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 2318 of file catch.hpp.
{
             return { static_cast<bool>(m_lhs < rhs), m_lhs, "<", rhs };
         }
References Catch::ExprLhs< LhsT >::m_lhs.
operator<=()
template<typename LhsT > template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator<= (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 2326 of file catch.hpp.
{
             return { static_cast<bool>(m_lhs <= rhs), m_lhs, "<=", rhs };
         }
References Catch::ExprLhs< LhsT >::m_lhs.
operator==() [1/2]
template<typename LhsT > auto Catch::ExprLhs< LhsT >::operator== (bool rhs) -> BinaryExpr<LhsT, bool> const inline
Definition at line 2301 of file catch.hpp.
{
             return { m_lhs == rhs, m_lhs, "==", rhs };
         }
References Catch::ExprLhs< LhsT >::m_lhs.
operator==() [2/2]
template<typename LhsT > template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator== (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 2298 of file catch.hpp.
{
             return { compareEqual( m_lhs, rhs ), m_lhs, "==", rhs };
         }
References Catch::compareEqual(), and Catch::ExprLhs< LhsT >::m_lhs.
operator>()
template<typename LhsT > template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator> (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 2314 of file catch.hpp.
{
             return { static_cast<bool>(m_lhs > rhs), m_lhs, ">", rhs };
         }
References Catch::ExprLhs< LhsT >::m_lhs.
operator>=()
template<typename LhsT > template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator>= (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 2322 of file catch.hpp.
{
             return { static_cast<bool>(m_lhs >= rhs), m_lhs, ">=", rhs };
         }
References Catch::ExprLhs< LhsT >::m_lhs.
operator||()
template<typename LhsT > template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator|| (RhsT const &) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 2338 of file catch.hpp.
{
             static_assert(always_false<RhsT>::value,
             "operator|| is not supported inside assertions, "
             "wrap the expression inside parentheses, or decompose it");
         }
Field Documentation
m_lhs
template<typename LhsT > LhsT Catch::ExprLhs< LhsT >::m_lhs private
Definition at line 2293 of file catch.hpp.
Referenced by Catch::ExprLhs< LhsT >::makeUnaryExpr(), Catch::ExprLhs< LhsT >::operator!=(), Catch::ExprLhs< LhsT >::operator<(), Catch::ExprLhs< LhsT >::operator<=(), Catch::ExprLhs< LhsT >::operator==(), Catch::ExprLhs< LhsT >::operator>(), and Catch::ExprLhs< LhsT >::operator>=().
The documentation for this class was generated from the following file:
catch.hpp