Quantum Exact Simulation Toolkit: Catch::ReusableStringStream Class Reference
Catch::ReusableStringStream Class Reference
#include <catch.hpp>
Public Member Functions
auto get () -> std::ostream &
template<typename T >
auto operator<< (T const &value) -> ReusableStringStream &
ReusableStringStream ()
auto str () const -> std::string
~ReusableStringStream ()
Private Attributes
std::size_t m_index
std::ostream * m_oss
Detailed Description
Definition at line 1401 of file catch.hpp.
Constructor & Destructor Documentation
ReusableStringStream()
Catch::ReusableStringStream::ReusableStringStream ()
~ReusableStringStream()
Catch::ReusableStringStream::~ReusableStringStream ()
Member Function Documentation
get()
auto Catch::ReusableStringStream::get () -> std::ostream& inline
Definition at line 1415 of file catch.hpp.
 { return *m_oss; }
References m_oss.
operator<<()
template<typename T > auto Catch::ReusableStringStream::operator<< (T const & value) -> ReusableStringStream& inline
Definition at line 1411 of file catch.hpp.
{
             *m_oss << value;
             return *this;
         }
References m_oss, and Catch::Generators::value().
str()
auto Catch::ReusableStringStream::str () const -> std::string
Referenced by Catch::StringMaker< T, typename >::convert(), Catch::Detail::rangeToString(), and Catch::rangeToString().
Field Documentation
m_index
std::size_t Catch::ReusableStringStream::m_index private
Definition at line 1402 of file catch.hpp.
m_oss
std::ostream* Catch::ReusableStringStream::m_oss private
Definition at line 1403 of file catch.hpp.
Referenced by get(), and operator<<().
The documentation for this class was generated from the following file:
catch.hpp