Quantum Exact Simulation Toolkit: Debugging
Debugging
Utilities for seeding and debugging, such as state-logging.
Functions
void getEnvironmentString (QuESTEnv env, Qureg qureg, char str[200])
Sets str to a string containing the number of qubits in qureg, and the hardware facilities used (e.g.
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
void reportQuregParams (Qureg qureg)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
void reportState (Qureg qureg)
Print the current state vector of probability amplitudes for a set of qubits to file.
void reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
void seedQuEST (unsigned long int *seedArray, int numSeeds)
Seed the Mersenne Twister used for random number generation in the QuEST environment with a user defined seed.
void seedQuESTDefault (void)
Seed the Mersenne Twister used for random number generation in the QuEST environment with an example defualt seed.
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
Detailed Description
Utilities for seeding and debugging, such as state-logging.
Author
Ania Brown
Tyson Jones
Balint Koczor (Kraus maps)
Nicolas Vogt of HQS (one-qubit damping)
Function Documentation
getEnvironmentString()
void getEnvironmentString (QuESTEnv env, Qureg qureg, char str[200])
Sets str to a string containing the number of qubits in qureg, and the hardware facilities used (e.g.
GPU, MPI and/or OMP).
Parameters
[in] env object representing the execution environment. A single instance is used for each program
[in] qureg the qureg of which to query the simulating hardware
[out] str to be populated with the output string
Author
Ania Brown
Definition at line 386 of file QuEST_gpu.cu.
{
     sprintf(str, "%dqubits_GPU_noMpi_noOMP", qureg.numQubitsInStateVec);
 }
References Qureg::numQubitsInStateVec.
reportQuESTEnv()
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Author
Ania Brown
Definition at line 175 of file QuEST_cpu_distributed.c.
{
     if (env.rank==0){
         printf("EXECUTION ENVIRONMENT:\n");
         printf("Running distributed (MPI) version\n");
         printf("Number of ranks is %d\n", env.numRanks);
 # ifdef _OPENMP
         printf("OpenMP enabled\n");
         printf("Number of threads available is %d\n", omp_get_max_threads());
 # else
         printf("OpenMP disabled\n");
 # endif
         printf("Precision: size of qreal is %ld bytes\n", sizeof(qreal) );
     }
 }
References QuESTEnv::numRanks, qreal, and QuESTEnv::rank.
reportQuregParams()
void reportQuregParams (Qureg qureg)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
Parameters
[in] qureg object representing the set of qubits
Author
Ania Brown
Definition at line 234 of file QuEST_common.c.
{
     long long int numAmps = 1LL << qureg.numQubitsInStateVec;
     long long int numAmpsPerRank = numAmps/qureg.numChunks;
     if (qureg.chunkId==0){
         printf("QUBITS:\n");
         printf("Number of qubits is %d.\n", qureg.numQubitsInStateVec);
         printf("Number of amps is %lld.\n", numAmps);
         printf("Number of amps per rank is %lld.\n", numAmpsPerRank);
     }
 }
References Qureg::chunkId, Qureg::numChunks, and Qureg::numQubitsInStateVec.
reportState()
void reportState (Qureg qureg)
Print the current state vector of probability amplitudes for a set of qubits to file.
File format:
real, imag
realComponent1, imagComponent1
realComponent2, imagComponent2
...
realComponentN, imagComponentN
File naming convention:
For each node that the program runs on, a file 'state_rank_[node_rank].csv' is generated. If there is more than one node, ranks after the first do not include the header
real, imag
so that files are easier to combine.
Parameters
[in,out] qureg object representing the set of qubits
Author
Ania Brown
Definition at line 216 of file QuEST_common.c.
{
     FILE *state;
     char filename[100];
     long long int index;
     sprintf(filename, "state_rank_%d.csv", qureg.chunkId);
     state = fopen(filename, "w");
     if (qureg.chunkId==0) fprintf(state, "real, imag\n");
     for(index=0; index<qureg.numAmpsPerChunk; index++){
         # if QuEST_PREC==1 || QuEST_PREC==2
         fprintf(state, "%.12f, %.12f\n", qureg.stateVec.real[index], qureg.stateVec.imag[index]);
         # elif QuEST_PREC == 4
         fprintf(state, "%.12Lf, %.12Lf\n", qureg.stateVec.real[index], qureg.stateVec.imag[index]);
         #endif
     }
     fclose(state);
 }
References Qureg::chunkId, Qureg::numAmpsPerChunk, and Qureg::stateVec.
reportStateToScreen()
void reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
For debugging purposes. Each rank should print output serially. Only print output for systems <= 5 qubits
Author
Ania Brown
Definition at line 1057 of file QuEST.c.
{
     statevec_reportStateToScreen(qureg, env, reportRank);
 }
References statevec_reportStateToScreen().
seedQuEST()
void seedQuEST (unsigned long int * seedArray, int numSeeds)
Seed the Mersenne Twister used for random number generation in the QuEST environment with a user defined seed.
This function uses the mt19937 init_by_array function with numSeeds keys supplied by the user. Subsequent calls to mt19937 genrand functions will use this seeding. For a multi process code, the same seed is given to all process, therefore this seeding is only appropriate to use for functions such as measure where all processes require the same random value.
For more information about the MT, see http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/MT2002/emt19937ar.html
Parameters
[in] seedArray Array of integers to use as seed. This allows the MT to be initialised with more than a 32-bit integer if required
[in] numSeeds Length of seedArray
Author
Ania Brown
Seed the Mersenne Twister used for random number generation in the QuEST environment with a user defined seed.
Definition at line 209 of file QuEST_common.c.
{
     // init MT random number generator with user defined list of seeds
     // for the MPI version, it is ok that all procs will get the same seed as random numbers will only be
     // used by the master process
     init_by_array(seedArray, numSeeds);
 }
References init_by_array().
seedQuESTDefault()
void seedQuESTDefault (void)
Seed the Mersenne Twister used for random number generation in the QuEST environment with an example defualt seed.
This default seeding function uses the mt19937 init_by_array function with two keys – time and pid. Subsequent calls to mt19937 genrand functions will use this seeding. For a multi process code, the same seed is given to all process, therefore this seeding is only appropriate to use for functions such as measure where all processes require the same random value.
For more information about the MT, see http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/MT2002/emt19937ar.html
Author
Ania Brown
Balint Koczor (Windows compatibility)
Definition at line 1306 of file QuEST_cpu_distributed.c.
{
     // init MT random number generator with three keys -- time and pid
     // for the MPI version, it is ok that all procs will get the same seed as random numbers will only be
     // used by the master process
     unsigned long int key[2];
     getQuESTDefaultSeedKey(key);
     // this seed will be used to generate the same random number on all procs,
     // therefore we want to make sure all procs receive the same key
     MPI_Bcast(key, 2, MPI_UNSIGNED_LONG, 0, MPI_COMM_WORLD);
     init_by_array(key, 2);
 }
References getQuESTDefaultSeedKey(), and init_by_array().
Referenced by createQuESTEnv().
syncQuESTEnv()
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Author
Ania Brown
Definition at line 158 of file QuEST_cpu_distributed.c.
{
     MPI_Barrier(MPI_COMM_WORLD);
 }
Referenced by statevec_initStateFromSingleFile(), and statevec_reportStateToScreen().
syncQuESTSuccess()
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
If any one process has a zero successCode all processes will return a zero success code.
Parameters
[in] successCode 1 if process task succeeded, 0 if process task failed
Returns
1 if all processes succeeded, 0 if any one process failed
Author
Ania Brown
Definition at line 162 of file QuEST_cpu_distributed.c.
{
     int totalSuccess;
     MPI_Allreduce(&successCode, &totalSuccess, 1, MPI_INT, MPI_LAND, MPI_COMM_WORLD);
     return totalSuccess;
 }