Quantum Exact Simulation Toolkit: Catch::Generators::pf Namespace Reference
Catch::Generators::pf Namespace Reference
Functions
template<typename T , typename... Args>
std::unique_ptr< T > make_unique (Args &&... args)
Function Documentation
make_unique()
template<typename T , typename... Args> std::unique_ptr<T> Catch::Generators::pf::make_unique (Args &&... args)
Definition at line 3869 of file catch.hpp.
{
             return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
         }
Referenced by Catch::Generators::filter(), Catch::Generators::from_range(), Catch::Generators::generate(), Catch::Generators::map(), Catch::Generators::random(), Catch::Generators::range(), Catch::Generators::repeat(), Catch::Generators::take(), Catch::Generators::value(), and Catch::Generators::values().