Quantum Exact Simulation Toolkit: Catch::Generators Namespace Reference
Catch::Generators Namespace Reference
Namespaces
pf
Data Structures
struct as
class ChunkGenerator
class FilterGenerator
class FixedValuesGenerator
class Generators
class GeneratorUntypedBase
class GeneratorWrapper
struct IGenerator
class IteratorGenerator
class MapGenerator
class RandomFloatingGenerator
class RandomIntegerGenerator
class RangeGenerator
class RepeatGenerator
class SingleValueGenerator
class TakeGenerator
Typedefs
using GeneratorBasePtr = std::unique_ptr< GeneratorUntypedBase >
template<typename Func , typename U >
using MapFunctionReturnType = typename std::remove_reference< typename std::remove_cv< typename std::result_of< Func(U)>::type >::type >::type
Functions
auto acquireGeneratorTracker (SourceLineInfo const &lineInfo) -> IGeneratorTracker &
template<typename T >
GeneratorWrapper< std::vector< T > > chunk (size_t size, GeneratorWrapper< T > &&generator)
template<typename T , typename Predicate >
GeneratorWrapper< T > filter (Predicate &&pred, GeneratorWrapper< T > &&generator)
template<typename Container , typename ResultType = typename Container::value_type>
GeneratorWrapper< ResultType > from_range (Container const &cnt)
template<typename InputIterator , typename InputSentinel , typename ResultType = typename std::iterator_traits<InputIterator>::value_type>
GeneratorWrapper< ResultType > from_range (InputIterator from, InputSentinel to)
template<typename L >
auto generate (SourceLineInfo const &lineInfo, L const &generatorExpression) -> decltype(std::declval< decltype(generatorExpression())>().get())
template<typename T , typename U , typename... Gs>
auto makeGenerators (as< T >, U &&val, Gs... moreGenerators) -> Generators< T >
template<typename T >
auto makeGenerators (GeneratorWrapper< T > &&generator) -> Generators< T >
template<typename T , typename... Gs>
auto makeGenerators (GeneratorWrapper< T > &&generator, Gs... moreGenerators) -> Generators< T >
template<typename T , typename... Gs>
auto makeGenerators (T &&val, Gs... moreGenerators) -> Generators< T >
template<typename Func , typename U , typename T = MapFunctionReturnType<Func, U>>
GeneratorWrapper< T > map (Func &&function, GeneratorWrapper< U > &&generator)
template<typename T >
std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value, GeneratorWrapper< T > >::type random (T a, T b)
template<typename T >
std::enable_if< std::is_floating_point< T >::value, GeneratorWrapper< T > >::type random (T a, T b)
template<typename T >
GeneratorWrapper< T > range (T const &start, T const &end)
template<typename T >
GeneratorWrapper< T > range (T const &start, T const &end, T const &step)
template<typename T >
GeneratorWrapper< T > repeat (size_t repeats, GeneratorWrapper< T > &&generator)
template<typename... Ts>
GeneratorWrapper< std::tuple< Ts... > > table (std::initializer_list< std::tuple< typename std::decay< Ts >::type... >> tuples)
template<typename T >
GeneratorWrapper< T > take (size_t target, GeneratorWrapper< T > &&generator)
template<typename T >
GeneratorWrapper< T > value (T &&value)
template<typename T >
GeneratorWrapper< T > values (std::initializer_list< T > values)
Typedef Documentation
GeneratorBasePtr
using Catch::Generators::GeneratorBasePtr = typedef std::unique_ptr<GeneratorUntypedBase>
Definition at line 3789 of file catch.hpp.
MapFunctionReturnType
template<typename Func , typename U > using Catch::Generators::MapFunctionReturnType = typedef typename std::remove_reference<typename std::remove_cv<typename std::result_of<Func(U)>::type>::type>::type
Definition at line 4214 of file catch.hpp.
Function Documentation
acquireGeneratorTracker()
auto Catch::Generators::acquireGeneratorTracker (SourceLineInfo const & lineInfo) -> IGeneratorTracker &
Referenced by generate().
chunk()
template<typename T > GeneratorWrapper<std::vector<T> > Catch::Generators::chunk (size_t size, GeneratorWrapper< T > && generator)
Definition at line 4268 of file catch.hpp.
{
         return GeneratorWrapper<std::vector<T>>(
             pf::make_unique<ChunkGenerator<T>>(size, std::move(generator))
         );
     }
filter()
template<typename T , typename Predicate > GeneratorWrapper<T> Catch::Generators::filter (Predicate && pred, GeneratorWrapper< T > && generator)
Definition at line 4119 of file catch.hpp.
{
         return GeneratorWrapper<T>(std::unique_ptr<IGenerator<T>>(pf::make_unique<FilterGenerator<T, Predicate>>(std::forward<Predicate>(pred), std::move(generator))));
     }
References Catch::Generators::pf::make_unique().
Referenced by TEST_CASE().
from_range() [1/2]
template<typename Container , typename ResultType = typename Container::value_type> GeneratorWrapper<ResultType> Catch::Generators::from_range (Container const & cnt)
Definition at line 4677 of file catch.hpp.
{
     return GeneratorWrapper<ResultType>(pf::make_unique<IteratorGenerator<ResultType>>(cnt.begin(), cnt.end()));
 }
References Catch::Generators::pf::make_unique().
from_range() [2/2]
template<typename InputIterator , typename InputSentinel , typename ResultType = typename std::iterator_traits<InputIterator>::value_type> GeneratorWrapper<ResultType> Catch::Generators::from_range (InputIterator from, InputSentinel to)
Definition at line 4671 of file catch.hpp.
{
     return GeneratorWrapper<ResultType>(pf::make_unique<IteratorGenerator<ResultType>>(from, to));
 }
References Catch::Generators::pf::make_unique().
generate()
template<typename L > auto Catch::Generators::generate (SourceLineInfo const & lineInfo, L const & generatorExpression) -> decltype(std::declval<decltype(generatorExpression())>().get())
Definition at line 4020 of file catch.hpp.
{
         using UnderlyingType = typename decltype(generatorExpression())::type;
         IGeneratorTracker& tracker = acquireGeneratorTracker( lineInfo );
         if (!tracker.hasGenerator()) {
             tracker.setGenerator(pf::make_unique<Generators<UnderlyingType>>(generatorExpression()));
         }
         auto const& generator = static_cast<IGenerator<UnderlyingType> const&>( *tracker.getGenerator() );
         return generator.get();
     }
References acquireGeneratorTracker(), Catch::Generators::IGenerator< T >::get(), Catch::IGeneratorTracker::getGenerator(), Catch::IGeneratorTracker::hasGenerator(), Catch::Generators::pf::make_unique(), and Catch::IGeneratorTracker::setGenerator().
makeGenerators() [1/4]
template<typename T , typename U , typename... Gs> auto Catch::Generators::makeGenerators (as< T > , U && val, Gs... moreGenerators) -> Generators<T>
Definition at line 4010 of file catch.hpp.
{
         return makeGenerators( value( T( std::forward<U>( val ) ) ), std::forward<Gs>( moreGenerators )... );
     }
References value().
Referenced by makeGenerators().
makeGenerators() [2/4]
template<typename T > auto Catch::Generators::makeGenerators (GeneratorWrapper< T > && generator) -> Generators<T>
Definition at line 4002 of file catch.hpp.
{
         return Generators<T>(std::move(generator));
     }
makeGenerators() [3/4]
template<typename T , typename... Gs> auto Catch::Generators::makeGenerators (GeneratorWrapper< T > && generator, Gs... moreGenerators) -> Generators<T>
Definition at line 3998 of file catch.hpp.
{
         return Generators<T>(std::move(generator), std::forward<Gs>(moreGenerators)...);
     }
makeGenerators() [4/4]
template<typename T , typename... Gs> auto Catch::Generators::makeGenerators (T && val, Gs... moreGenerators) -> Generators<T>
Definition at line 4006 of file catch.hpp.
{
         return makeGenerators( value( std::forward<T>( val ) ), std::forward<Gs>( moreGenerators )... );
     }
References makeGenerators(), and value().
map()
template<typename Func , typename U , typename T = MapFunctionReturnType<Func, U>> GeneratorWrapper< T > Catch::Generators::map (Func && function, GeneratorWrapper< U > && generator)
Definition at line 4218 of file catch.hpp.
{
         return GeneratorWrapper<T>(
             pf::make_unique<MapGenerator<T, U, Func>>(std::forward<Func>(function), std::move(generator))
         );
     }
References Catch::Generators::pf::make_unique().
random() [1/2]
template<typename T > std::enable_if<std::is_integral<T>::value && !std::is_same<T, bool>::value,GeneratorWrapper<T> >::type Catch::Generators::random (T a, T b)
Definition at line 4582 of file catch.hpp.
                  {
     return GeneratorWrapper<T>(
         pf::make_unique<RandomIntegerGenerator<T>>(a, b)
     );
 }
References Catch::Generators::pf::make_unique().
Referenced by TEST_CASE().
random() [2/2]
template<typename T > std::enable_if<std::is_floating_point<T>::value,GeneratorWrapper<T> >::type Catch::Generators::random (T a, T b)
Definition at line 4591 of file catch.hpp.
                  {
     return GeneratorWrapper<T>(
         pf::make_unique<RandomFloatingGenerator<T>>(a, b)
     );
 }
References Catch::Generators::pf::make_unique().
range() [1/2]
template<typename T > GeneratorWrapper<T> Catch::Generators::range (T const & start, T const & end)
Definition at line 4637 of file catch.hpp.
{
     static_assert(std::is_integral<T>::value && !std::is_same<T, bool>::value, "Type must be an integer");
     return GeneratorWrapper<T>(pf::make_unique<RangeGenerator<T>>(start, end));
 }
References Catch::end, Catch::Generators::pf::make_unique(), and value().
Referenced by Catch::StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >::convert(), and Catch::rangeToString().
range() [2/2]
template<typename T > GeneratorWrapper<T> Catch::Generators::range (T const & start, T const & end, T const & step)
Definition at line 4631 of file catch.hpp.
{
     static_assert(std::is_integral<T>::value && !std::is_same<T, bool>::value, "Type must be an integer");
     return GeneratorWrapper<T>(pf::make_unique<RangeGenerator<T>>(start, end, step));
 }
References Catch::end, Catch::Generators::pf::make_unique(), and value().
Referenced by TEST_CASE().
repeat()
template<typename T > GeneratorWrapper<T> Catch::Generators::repeat (size_t repeats, GeneratorWrapper< T > && generator)
Definition at line 4175 of file catch.hpp.
{
         return GeneratorWrapper<T>(pf::make_unique<RepeatGenerator<T>>(repeats, std::move(generator)));
     }
References Catch::Generators::pf::make_unique().
table()
template<typename... Ts> GeneratorWrapper<std::tuple<Ts...> > Catch::Generators::table (std::initializer_list< std::tuple< typename std::decay< Ts >::type... >> tuples)
Definition at line 3989 of file catch.hpp.
{
         return values<std::tuple<Ts...>>( tuples );
     }
References values().
take()
template<typename T > GeneratorWrapper<T> Catch::Generators::take (size_t target, GeneratorWrapper< T > && generator)
Definition at line 4080 of file catch.hpp.
{
         return GeneratorWrapper<T>(pf::make_unique<TakeGenerator<T>>(target, std::move(generator)));
     }
References Catch::Generators::pf::make_unique().
Referenced by TEST_CASE().
value()
template<typename T > GeneratorWrapper<T> Catch::Generators::value (T && value)
Definition at line 3936 of file catch.hpp.
{
         return GeneratorWrapper<T>(pf::make_unique<SingleValueGenerator<T>>(std::forward<T>(value)));
     }
References Catch::Generators::pf::make_unique().
Referenced by Catch::Capturer::captureValues(), Catch::StringMaker< T, typename >::convert(), Catch::Detail::convertUnstreamable(), makeGenerators(), Catch::Detail::Approx::operator()(), Catch::operator+(), Catch::ReusableStringStream::operator<<(), Catch::MessageStream::operator<<(), Catch::MessageBuilder::operator<<(), Catch::Decomposer::operator<=(), Catch::Generators::Generators< T >::populate(), range(), statevec_calcExpecPauliProd(), and statevec_calcExpecPauliSum().
values()
template<typename T > GeneratorWrapper<T> Catch::Generators::values (std::initializer_list< T > values)
Definition at line 3940 of file catch.hpp.
{
         return GeneratorWrapper<T>(pf::make_unique<FixedValuesGenerator<T>>(values));
     }
References Catch::Generators::pf::make_unique().
Referenced by Catch::Capturer::captureValues(), Catch::IMutableEnumValuesRegistry::registerEnum(), and table().