Quantum Exact Simulation Toolkit: Catch::Detail Namespace Reference
Catch::Detail Namespace Reference
Data Structures
class Approx
struct EnumInfo
class IsStreamInsertable
Functions
template<typename E >
std::string convertUnknownEnumToString (E e)
template<typename T >
std::enable_if< !std::is_enum< T >::value &&!std::is_base_of< std::exception, T >::value, std::string >::type convertUnstreamable (T const &)
template<typename T >
std::enable_if< !std::is_enum< T >::value &&std::is_base_of< std::exception, T >::value, std::string >::type convertUnstreamable (T const &ex)
template<typename T >
std::enable_if< std::is_enum< T >::value, std::string >::type convertUnstreamable (T const &value)
template<typename InputIterator >
std::string rangeToString (InputIterator first, InputIterator last)
template<typename T >
std::string rawMemoryToString (const T &object)
std::string rawMemoryToString (const void *object, std::size_t size)
template<typename T >
std::string stringify (const T &e)
Variables
const std::string unprintableString
Function Documentation
convertUnknownEnumToString()
template<typename E > std::string Catch::Detail::convertUnknownEnumToString (E e)
Definition at line 1610 of file catch.hpp.
{
             return ::Catch::Detail::stringify(static_cast<typename std::underlying_type<E>::type>(e));
         }
References stringify().
Referenced by convertUnstreamable().
convertUnstreamable() [1/3]
template<typename T > std::enable_if< !std::is_enum<T>::value && !std::is_base_of<std::exception, T>::value, std::string>::type Catch::Detail::convertUnstreamable (T const &)
Definition at line 1543 of file catch.hpp.
{
             return Detail::unprintableString;
         }
References unprintableString.
Referenced by Catch::StringMaker< T, typename >::convert().
convertUnstreamable() [2/3]
template<typename T > std::enable_if< !std::is_enum<T>::value && std::is_base_of<std::exception, T>::value, std::string>::type Catch::Detail::convertUnstreamable (T const & ex)
Definition at line 1549 of file catch.hpp.
{
             return ex.what();
         }
convertUnstreamable() [3/3]
template<typename T > std::enable_if< std::is_enum<T>::value , std::string>::type Catch::Detail::convertUnstreamable (T const & value)
Definition at line 1556 of file catch.hpp.
{
             return convertUnknownEnumToString( value );
         }
References convertUnknownEnumToString(), and Catch::Generators::value().
rangeToString()
template<typename InputIterator > std::string Catch::Detail::rangeToString (InputIterator first, InputIterator last)
Definition at line 1790 of file catch.hpp.
{
             ReusableStringStream rss;
             rss << "{ ";
             if (first != last) {
                 rss << ::Catch::Detail::stringify(*first);
                 for (++first; first != last; ++first)
                     rss << ", " << ::Catch::Detail::stringify(*first);
             }
             rss << " }";
             return rss.str();
         }
References Catch::ReusableStringStream::str(), and stringify().
rawMemoryToString() [1/2]
template<typename T > std::string Catch::Detail::rawMemoryToString (const T & object)
Definition at line 1520 of file catch.hpp.
{
           return rawMemoryToString( &object, sizeof(object) );
         }
References rawMemoryToString().
Referenced by Catch::StringMaker< T * >::convert(), and Catch::StringMaker< R C::* >::convert().
rawMemoryToString() [2/2]
std::string Catch::Detail::rawMemoryToString (const void * object, std::size_t size)
Referenced by rawMemoryToString().
stringify()
template<typename T > std::string Catch::Detail::stringify (const T & e)
Definition at line 1605 of file catch.hpp.
{
             return ::Catch::StringMaker<typename std::remove_cv<typename std::remove_reference<T>::type>::type>::convert(e);
         }
Referenced by Catch::Capturer::captureValues(), Catch::StringMaker< char[SZ]>::convert(), Catch::StringMaker< signed char[SZ]>::convert(), Catch::StringMaker< unsigned char[SZ]>::convert(), convertUnknownEnumToString(), Catch::Matchers::Vector::ContainsElementMatcher< T >::describe(), Catch::Matchers::Vector::ContainsMatcher< T >::describe(), Catch::Matchers::Vector::EqualsMatcher< T >::describe(), Catch::Matchers::Vector::ApproxMatcher< T >::describe(), Catch::Matchers::Vector::UnorderedEqualsMatcher< T >::describe(), rangeToString(), Catch::rangeToString(), Catch::BinaryExpr< LhsT, RhsT >::streamReconstructedExpression(), Catch::UnaryExpr< LhsT >::streamReconstructedExpression(), and Catch::MatchExpr< ArgT, MatcherT >::streamReconstructedExpression().
Variable Documentation
unprintableString
const std::string Catch::Detail::unprintableString
Referenced by convertUnstreamable(), and Catch::MatchExpr< ArgT, MatcherT >::streamReconstructedExpression().