Quantum Exact Simulation Toolkit: QuEST.c File Reference
QuEST.c File Reference
Implements the QuEST.h API (and some debugging functions) in a hardware-agnostic way, for both pure and mixed states.
#include "QuEST.h"
#include "QuEST_precision.h"
#include "QuEST_internal.h"
#include "QuEST_validation.h"
#include "QuEST_qasm.h"
#include <stdlib.h>
Functions
void applyDiagonalOperator (Qureg qureg, DiagonalOperator op)
Applies op to qureg, which must be a pure state-vector of equal dimension (number of qubits) to op.
void applyPauliSum (Qureg inQureg, enum pauliOpType *allPauliCodes, qreal *termCoeffs, int numSumTerms, Qureg outQureg)
Modifies outQureg to be the result of applying the weighted sum of Pauli products (a Hermitian but not necessarily unitary operator) to inQureg.
qreal calcExpecPauliProd (Qureg qureg, int *targetQubits, enum pauliOpType *pauliCodes, int numTargets, Qureg workspace)
Computes the expected value of a product of Pauli operators.
qreal calcExpecPauliSum (Qureg qureg, enum pauliOpType *allPauliCodes, qreal *termCoeffs, int numSumTerms, Qureg workspace)
Computes the expected value of a sum of products of Pauli operators.
qreal calcFidelity (Qureg qureg, Qureg pureState)
Calculates the fidelity of qureg (a statevector or density matrix) against a reference pure state (necessarily a statevector).
qreal calcHilbertSchmidtDistance (Qureg a, Qureg b)
Computes the Hilbert Schmidt distance between two density matrices a and b, defined as the Frobenius norm of the difference between them.
Complex calcInnerProduct (Qureg bra, Qureg ket)
Computes the inner product of two equal-size state vectors.
qreal calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
qreal calcPurity (Qureg qureg)
Calculates the purity of a density matrix, by the trace of the density matrix squared.
qreal calcTotalProb (Qureg qureg)
A debugging function which calculates the probability of being in any state, which should always be 1.
void clearRecordedQASM (Qureg qureg)
Clear all QASM so far recorded.
void cloneQureg (Qureg targetQureg, Qureg copyQureg)
Set targetQureg to be a clone of copyQureg.
qreal collapseToOutcome (Qureg qureg, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
void compactUnitary (Qureg qureg, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
int compareStates (Qureg qureg1, Qureg qureg2, qreal precision)
Return whether two given wavefunctions are equivalent within a given precision Global phase included in equivalence check.
void controlledCompactUnitary (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
void controlledMultiQubitUnitary (Qureg qureg, int ctrl, int *targs, const int numTargs, ComplexMatrixN u)
Apply a general controlled multi-qubit unitary (including a global phase factor).
void controlledNot (Qureg qureg, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
void controlledPauliY (Qureg qureg, const int controlQubit, const int targetQubit)
Apply the controlled pauliY (single control, single target) gate, also known as the c-Y and c-sigma-Y gate.
void controlledPhaseFlip (Qureg qureg, const int idQubit1, const int idQubit2)
Apply the (two-qubit) controlled phase flip gate, also known as the controlled pauliZ gate.
void controlledPhaseShift (Qureg qureg, const int idQubit1, const int idQubit2, qreal angle)
Introduce a phase factor on state of qubits idQubit1 and idQubit2.
void controlledRotateAroundAxis (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle, Vector axis)
Applies a controlled rotation by a given angle around a given vector on the Bloch-sphere.
void controlledRotateX (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the X-axis of the Bloch-sphere.
void controlledRotateY (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the Y-axis of the Bloch-sphere.
void controlledRotateZ (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the Z-axis of the Bloch-sphere.
void controlledTwoQubitUnitary (Qureg qureg, const int controlQubit, const int targetQubit1, const int targetQubit2, ComplexMatrix4 u)
Apply a general controlled two-qubit unitary (including a global phase factor).
void controlledUnitary (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
Qureg createCloneQureg (Qureg qureg, QuESTEnv env)
Create a new Qureg which is an exact clone of the passed qureg, which can be either a statevector or a density matrix.
ComplexMatrixN createComplexMatrixN (int numQubits)
Create (dynamically) a square complex matrix which can be passed to the multi-qubit general unitary functions.
Qureg createDensityQureg (int numQubits, QuESTEnv env)
Create a Qureg for qubits which are represented by a density matrix, and can be in mixed states.
Qureg createQureg (int numQubits, QuESTEnv env)
Create a Qureg object representing a set of qubits which will remain in a pure state.
void destroyComplexMatrixN (ComplexMatrixN m)
Destroy a ComplexMatrixN instance created with createComplexMatrixN()
void destroyQureg (Qureg qureg, QuESTEnv env)
Deallocate a Qureg object representing a set of qubits.
Complex getAmp (Qureg qureg, long long int index)
Get the complex amplitude at a given index in the state vector.
Complex getDensityAmp (Qureg qureg, long long int row, long long int col)
Get an amplitude from a density matrix at a given row and column.
qreal getImagAmp (Qureg qureg, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
long long int getNumAmps (Qureg qureg)
Get the number of probability amplitudes in a qureg object, given by 2^numQubits.
int getNumQubits (Qureg qureg)
Get the number of qubits in a qureg object.
qreal getProbAmp (Qureg qureg, long long int index)
Get the probability of the state at an index in the full state vector.
int getQuEST_PREC (void)
qreal getRealAmp (Qureg qureg, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
void hadamard (Qureg qureg, const int targetQubit)
Apply the single-qubit Hadamard gate.
void initBlankState (Qureg qureg)
Initialises a qureg to have all-zero-amplitudes.
void initClassicalState (Qureg qureg, long long int stateInd)
Initialise a set of qubits to the classical state with index stateInd.
void initComplexMatrixN (ComplexMatrixN m, qreal re[][1<< m.numQubits], qreal im[][1<< m.numQubits])
Initialises a ComplexMatrixN instance to have the passed real and imag values.
void initPlusState (Qureg qureg)
Initialise a set of qubits to the plus state .
void initPureState (Qureg qureg, Qureg pure)
Initialise a set of qubits, which can be a state vector or density matrix, to a given pure state.
void initStateDebug (Qureg qureg)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
void initStateFromAmps (Qureg qureg, qreal *reals, qreal *imags)
Initialise qureg by specifying the complete statevector.
void initStateFromSingleFile (Qureg *qureg, char filename[200], QuESTEnv env)
Initialises the wavefunction amplitudes according to those specified in a file.
void initStateOfSingleQubit (Qureg *qureg, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
void initZeroState (Qureg qureg)
Initialise a set of qubits to the classical zero state .
int measure (Qureg qureg, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
int measureWithStats (Qureg qureg, int measureQubit, qreal *outcomeProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
void mixDamping (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit damping (decay to 0 state).
void mixDensityMatrix (Qureg combineQureg, qreal otherProb, Qureg otherQureg)
Modifies combineQureg to become (1-prob)combineProb + prob otherQureg.
void mixDephasing (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit dephasing noise.
void mixDepolarising (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit homogeneous depolarising noise.
void mixKrausMap (Qureg qureg, int target, ComplexMatrix2 *ops, int numOps)
Apply a general single-qubit Kraus map to a density matrix, as specified by at most four Kraus operators.
void mixMultiQubitKrausMap (Qureg qureg, int *targets, int numTargets, ComplexMatrixN *ops, int numOps)
Apply a general N-qubit Kraus map to a density matrix, as specified by at most (2N)^2 Kraus operators.
void mixPauli (Qureg qureg, int qubit, qreal probX, qreal probY, qreal probZ)
Mixes a density matrix qureg to induce general single-qubit Pauli noise.
void mixTwoQubitDephasing (Qureg qureg, int qubit1, int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit dephasing noise.
void mixTwoQubitDepolarising (Qureg qureg, int qubit1, int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit homogeneous depolarising noise.
void mixTwoQubitKrausMap (Qureg qureg, int target1, int target2, ComplexMatrix4 *ops, int numOps)
Apply a general two-qubit Kraus map to a density matrix, as specified by at most sixteen Kraus operators.
void multiControlledMultiQubitUnitary (Qureg qureg, int *ctrls, const int numCtrls, int *targs, const int numTargs, ComplexMatrixN u)
Apply a general multi-controlled multi-qubit unitary (including a global phase factor).
void multiControlledPhaseFlip (Qureg qureg, int *controlQubits, int numControlQubits)
Apply the multiple-qubit controlled phase flip gate, also known as the multiple-qubit controlled pauliZ gate.
void multiControlledPhaseShift (Qureg qureg, int *controlQubits, int numControlQubits, qreal angle)
Introduce a phase factor on state of the passed qubits.
void multiControlledTwoQubitUnitary (Qureg qureg, int *controlQubits, const int numControlQubits, const int targetQubit1, const int targetQubit2, ComplexMatrix4 u)
Apply a general multi-controlled two-qubit unitary (including a global phase factor).
void multiControlledUnitary (Qureg qureg, int *controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
void multiQubitUnitary (Qureg qureg, int *targs, const int numTargs, ComplexMatrixN u)
Apply a general multi-qubit unitary (including a global phase factor) with any number of target qubits.
void multiRotatePauli (Qureg qureg, int *targetQubits, enum pauliOpType *targetPaulis, int numTargets, qreal angle)
Apply a multi-qubit multi-Pauli rotation on a selected number of qubits.
void multiRotateZ (Qureg qureg, int *qubits, int numQubits, qreal angle)
Apply a multi-qubit Z rotation on a selected number of qubits.
void multiStateControlledUnitary (Qureg qureg, int *controlQubits, int *controlState, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control, conditioned on a specific bit sequence, single-target unitary, which can include a global phase factor.
void pauliX (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-X (also known as the X, sigma-X, NOT or bit-flip) gate.
void pauliY (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-Y (also known as the Y or sigma-Y) gate.
void pauliZ (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-Z (also known as the Z, sigma-Z or phase-flip) gate.
void phaseShift (Qureg qureg, const int targetQubit, qreal angle)
Shift the phase between and of a single qubit by a given angle.
void printRecordedQASM (Qureg qureg)
Print recorded QASM to stdout.
void reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
void rotateAroundAxis (Qureg qureg, const int rotQubit, qreal angle, Vector axis)
Rotate a single qubit by a given angle around a given vector on the Bloch-sphere.
void rotateX (Qureg qureg, const int targetQubit, qreal angle)
Rotate a single qubit by a given angle around the X-axis of the Bloch-sphere.
void rotateY (Qureg qureg, const int targetQubit, qreal angle)
Rotate a single qubit by a given angle around the Y-axis of the Bloch-sphere.
void rotateZ (Qureg qureg, const int targetQubit, qreal angle)
Rotate a single qubit by a given angle around the Z-axis of the Bloch-sphere (also known as a phase shift gate).
void setAmps (Qureg qureg, long long int startInd, qreal *reals, qreal *imags, long long int numAmps)
Edit qureg to adopt the subset of amplitudes passed in reals and imags.
void setDensityAmps (Qureg qureg, qreal *reals, qreal *imags)
Set elements in the underlying state vector represenation of a density matrix.
void setWeightedQureg (Complex fac1, Qureg qureg1, Complex fac2, Qureg qureg2, Complex facOut, Qureg out)
Modifies qureg out to the result of (facOut out + fac1 qureg1 + fac2 qureg2), imposing no constraints on normalisation.
void sGate (Qureg qureg, const int targetQubit)
Apply the single-qubit S gate.
void sqrtSwapGate (Qureg qureg, int qb1, int qb2)
Performs a sqrt SWAP gate between qubit1 and qubit2.
void startRecordingQASM (Qureg qureg)
Enable QASM recording.
void stopRecordingQASM (Qureg qureg)
Disable QASM recording.
void swapGate (Qureg qureg, int qb1, int qb2)
Performs a SWAP gate between qubit1 and qubit2.
void tGate (Qureg qureg, const int targetQubit)
Apply the single-qubit T gate.
void twoQubitUnitary (Qureg qureg, const int targetQubit1, const int targetQubit2, ComplexMatrix4 u)
Apply a general two-qubit unitary (including a global phase factor).
void unitary (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
void writeRecordedQASMToFile (Qureg qureg, char *filename)
Writes recorded QASM to a file, throwing an error if inaccessible.
Detailed Description
Implements the QuEST.h API (and some debugging functions) in a hardware-agnostic way, for both pure and mixed states.
These functions mostly wrap hardware-specific functions, and should never call eachother.
Density matrices rho of N qubits are flattened to appear as state-vectors |s> of 2N qubits. Operations U rho U^dag are implemented as U^* U |s> and make use of the pure state backend, and often don't need to explicitly compute U^*.
Definition in file QuEST.c.
Function Documentation
applyDiagonalOperator()
void applyDiagonalOperator (Qureg qureg, DiagonalOperator op)
Applies op to qureg, which must be a pure state-vector of equal dimension (number of qubits) to op.
In CPU mode, op.real and op.imag are multiplied onto qureg. In GPU mode, those values at the last call to syncDiagonalOperator will be used (stored in op.deviceOperator). There is no requirement that op be Hermitian.
Parameters
[in,out] qureg A statevector of equal dimension to op, to operate upon
[in] op An operator diagonal in the Z basis
Exceptions
exitWithError if qureg.numQubitsRepresented != op.numQubits, or if operator has not been allocated via createDiagonalOperator, or if qureg is not a statevector.
Definition at line 30 of file QuEST.c.
References qasm_recordComment(), statevec_applyDiagonalOperator(), validateDiagonalOperator(), and validateStateVecQureg().
{
     validateDiagonalOperator(qureg, op, __func__);
     validateStateVecQureg(qureg, __func__);
     statevec_applyDiagonalOperator(qureg, op);
     qasm_recordComment(qureg, "Here, the register was modified to an undisclosed and possibly unphysical state (applyDiagonalOperator).");
 }
applyPauliSum()
void applyPauliSum (Qureg inQureg, enum pauliOpType * allPauliCodes, qreal * termCoeffs, int numSumTerms, Qureg outQureg)
Modifies outQureg to be the result of applying the weighted sum of Pauli products (a Hermitian but not necessarily unitary operator) to inQureg.
Note that afterward, outQureg may not longer be normalised and ergo not a statevector or density matrix. Users must therefore be careful passing outQureg to other QuEST functions which assume normalisation in order to function correctly.
Letting be the operators indicated by allPauliCodes (where termCoeffs and qureg.numQubitsRepresented), this function effects on statevector and $ $ (matrix multiplication) on density matrix .
allPauliCodes is an array of length numSumTerms*qureg.numQubitsRepresented which specifies which Pauli operators to apply, where 0 = PAULI_I, 1 = PAULI_X, 2 = PAULI_Y, 3 = PAULI_Z. For each sum term, a Pauli operator must be specified for EVERY qubit in qureg; each set of numSumTerms operators will be grouped into a product. termCoeffs is an arrray of length numSumTerms containing the term coefficients. For example, on a 3-qubit statevector,
int paulis[6] = {PAULI_X, PAULI_I, PAULI_I,  PAULI_X, PAULI_Y, PAULI_Z};
qreal coeffs[2] = {1.5, -3.6};
applyPauliSum(inQureg, paulis, coeffs, 2, outQureg);
will apply Hermitian operation (where in this notation, the left-most operator applies to the least-significant qubit, i.e. that with index 0).
In theory, inQureg is unchanged though its state is temporarily modified and is reverted by re-applying Paulis (XX=YY=ZZ=I), so may see a change by small numerical errors. The initial state in outQureg is not used.
inQureg and outQureg must both be state-vectors, or both density matrices, of equal dimensions. inQureg cannot be outQureg.
This function works by applying each Pauli product to inQureg in turn, and adding the resulting state (weighted by a coefficient in termCoeffs) to the initially-blanked outQureg. Ergo it should scale with the total number of Pauli operators specified (excluding identities), and the qureg dimension.
Parameters
[in] inQureg the register containing the state which outQureg will be set to, under the action of the Hermitiain operator specified by the Pauli codes. inQureg should be unchanged, though may vary slightly due to numerical error.
[in] allPauliCodes a list of the Pauli codes (0=PAULI_I, 1=PAULI_X, 2=PAULI_Y, 3=PAULI_Z) of all Paulis involved in the products of terms. A Pauli must be specified for each qubit in the register, in every term of the sum.
[in] termCoeffs The coefficients of each term in the sum of Pauli products
[in] numSumTerms The total number of Pauli products specified
[out] outQureg the qureg to modify to be the result of applyling the weighted Pauli sum operator to the state in inQureg
Exceptions
exitWithError if any code in allPauliCodes is not in {0,1,2,3}, or if numSumTerms <= 0, or if inQureg is not of the same type and dimensions as outQureg
Definition at line 817 of file QuEST.c.
References Qureg::numQubitsRepresented, qasm_recordComment(), statevec_applyPauliSum(), validateMatchingQuregDims(), validateMatchingQuregTypes(), validateNumPauliSumTerms(), and validatePauliCodes().
{
     validateMatchingQuregTypes(inQureg, outQureg, __func__);
     validateMatchingQuregDims(inQureg, outQureg, __func__);
     validateNumPauliSumTerms(numSumTerms, __func__);
     validatePauliCodes(allPauliCodes, numSumTerms*inQureg.numQubitsRepresented, __func__);
     statevec_applyPauliSum(inQureg, allPauliCodes, termCoeffs, numSumTerms, outQureg);
     qasm_recordComment(outQureg, "Here, the register was modified to an undisclosed and possibly unphysical state (applyPauliSum).");
 }
calcExpecPauliProd()
qreal calcExpecPauliProd (Qureg qureg, int * targetQubits, enum pauliOpType * pauliCodes, int numTargets, Qureg workspace)
Computes the expected value of a product of Pauli operators.
Letting be the operators indicated by pauliCodes and acting on qubits targetQubits, this function computes if qureg = is a statevector, and computes if qureg = is a density matrix.
pauliCodes is an array of length numTargets which specifies which Pauli operators to enact on the corresponding qubits in targetQubits, where 0 = PAULI_I, 1 = PAULI_X, 2 = PAULI_Y, 3 = PAULI_Z. The target qubits must be unique, and at most qureg.numQubitsRepresented may be specified. For example, on a 7-qubit statevector,
calcExpecPauliProd(qureg, {4,5,6}, {PAULI_X, PAULI_I, PAULI_Z}, 3, workspace);
will compute (where in this notation, the left-most operator applies to the least-significant qubit, i.e. that with index 0).
workspace must be a register with the same type (statevector vs density matrix) and dimensions (numQubitsRepresented) as qureg, and is used as working space. When this function returns, qureg will be unchanged and workspace will be set to (if qureg is a statevector) or (if qureg is a density matrix). NOTE that this last quantity is NOT the result of applying the paulis as unitaries, , but is instead the result of their direct multiplication with the density matrix. It is therefore itself not a valid density matrix.
This function works by cloning the qureg state into workspace, applying the specified Pauli operators to workspace then computing its inner product with qureg (for statevectors) or its trace (for density matrices). It therefore should scale linearly in time with the number of specified non-identity Pauli operators, which is bounded by the number of represented qubits.
Parameters
[in] qureg the register of which to find the expected value, which is unchanged by this function
[in] targetQubits a list of the indices of the target qubits
[in] pauliCodes a list of the Pauli codes (0=PAULI_I, 1=PAULI_X, 2=PAULI_Y, 3=PAULI_Z) to apply to the corresponding qubits in targetQubits
[in] numTargets number of target qubits, i.e. the length of targetQubits and pauliCodes
[in,out] workspace a working-space qureg with the same dimensions as qureg, which is modified to be the result of multiplying the state with the pauli operators
Exceptions
exitWithError if numTargets is outside [1, qureg.numQubitsRepresented]), or if any qubit in targetQubits is outside [0, qureg.numQubitsRepresented)) or if any qubit in targetQubits is repeated, or if any code in pauliCodes is not in {0,1,2,3}, or if workspace is not of the same type and dimensions as qureg
Definition at line 874 of file QuEST.c.
References statevec_calcExpecPauliProd(), validateMatchingQuregDims(), validateMatchingQuregTypes(), validateMultiTargets(), and validatePauliCodes().
{
     validateMultiTargets(qureg, targetQubits, numTargets, __func__);
     validatePauliCodes(pauliCodes, numTargets, __func__);
     validateMatchingQuregTypes(qureg, workspace, __func__);
     validateMatchingQuregDims(qureg, workspace, __func__);
     return statevec_calcExpecPauliProd(qureg, targetQubits, pauliCodes, numTargets, workspace);
 }
calcExpecPauliSum()
qreal calcExpecPauliSum (Qureg qureg, enum pauliOpType * allPauliCodes, qreal * termCoeffs, int numSumTerms, Qureg workspace)
Computes the expected value of a sum of products of Pauli operators.
Letting be the operators indicated by allPauliCodes (where termCoeffs and qureg.numQubitsRepresented), this function computes if qureg = is a statevector, and computes if qureg = is a density matrix.
allPauliCodes is an array of length numSumTerms*qureg.numQubitsRepresented which specifies which Pauli operators to apply, where 0 = PAULI_I, 1 = PAULI_X, 2 = PAULI_Y, 3 = PAULI_Z. For each sum term, a Pauli operator must be specified for EVERY qubit in qureg; each set of numSumTerms operators will be grouped into a product. termCoeffs is an arrray of length numSumTerms containing the term coefficients. For example, on a 3-qubit statevector,
int paulis[6] = {PAULI_X, PAULI_I, PAULI_I,  PAULI_X, PAULI_Y, PAULI_Z};
qreal coeffs[2] = {1.5, -3.6};
calcExpecPauliSum(qureg, paulis, coeffs, 2, workspace);
will compute (where in this notation, the left-most operator applies to the least-significant qubit, i.e. that with index 0).
workspace must be a register with the same type (statevector vs density matrix) and dimensions (numQubitsRepresented) as qureg, and is used as working space. When this function returns, qureg will be unchanged and workspace will be set to qureg pre-multiplied with the final Pauli product. NOTE that if qureg is a density matrix, workspace will become which is itself not a density matrix (it is distinct from).
This function works by cloning the qureg state into workspace, applying each of the specified Pauli products to workspace (one Pauli operation at a time), then computing its inner product with qureg (for statevectors) or its trace (for density matrices) multiplied with the corresponding coefficient, and summing these contributions. It therefore should scale linearly in time with the total number of non-identity specified Pauli operators.
Parameters
[in] qureg the register of which to find the expected value, which is unchanged by this function
[in] allPauliCodes a list of the Pauli codes (0=PAULI_I, 1=PAULI_X, 2=PAULI_Y, 3=PAULI_Z) of all Paulis involved in the products of terms. A Pauli must be specified for each qubit in the register, in every term of the sum.
[in] termCoeffs The coefficients of each term in the sum of Pauli products
[in] numSumTerms The total number of Pauli products specified
[in,out] workspace a working-space qureg with the same dimensions as qureg, which is modified to be the result of multiplying the state with the final specified Pauli product
Exceptions
exitWithError if any code in allPauliCodes is not in {0,1,2,3}, or if numSumTerms <= 0, or if workspace is not of the same type and dimensions as qureg
Definition at line 883 of file QuEST.c.
References Qureg::numQubitsRepresented, statevec_calcExpecPauliSum(), validateMatchingQuregDims(), validateMatchingQuregTypes(), validateNumPauliSumTerms(), and validatePauliCodes().
{
     validateNumPauliSumTerms(numSumTerms, __func__);
     validatePauliCodes(allPauliCodes, numSumTerms*qureg.numQubitsRepresented, __func__);
     validateMatchingQuregTypes(qureg, workspace, __func__);
     validateMatchingQuregDims(qureg, workspace, __func__);
     return statevec_calcExpecPauliSum(qureg, allPauliCodes, termCoeffs, numSumTerms, workspace);
 }
calcFidelity()
qreal calcFidelity (Qureg qureg, Qureg pureState)
Calculates the fidelity of qureg (a statevector or density matrix) against a reference pure state (necessarily a statevector).
For two pure states, this computes
For a mixed and pure state, this computes
In either case, the fidelity lies in [0, 1]. The number of qubits represented in qureg and pureState must match.
Parameters
[in] qureg a density matrix or state vector
[in] pureState a state vector
Returns
the fidelity between the input registers
Exceptions
exitWithError if the second argument (pureState) is not a statevector, or if the number of qubits in qureg and pureState do not match
Definition at line 864 of file QuEST.c.
References densmatr_calcFidelity(), Qureg::isDensityMatrix, statevec_calcFidelity(), validateMatchingQuregDims(), and validateSecondQuregStateVec().
{
     validateSecondQuregStateVec(pureState, __func__);
     validateMatchingQuregDims(qureg, pureState, __func__);
     if (qureg.isDensityMatrix)
         return densmatr_calcFidelity(qureg, pureState);
     else
         return statevec_calcFidelity(qureg, pureState);
 }
calcHilbertSchmidtDistance()
qreal calcHilbertSchmidtDistance (Qureg a, Qureg b)
Computes the Hilbert Schmidt distance between two density matrices a and b, defined as the Frobenius norm of the difference between them.
That is, we define the Hilbert Schmidt distance
This is equivalent to the square-root of the sum of the absolute value squared of the element-differences of the matrices, i.e.
We caution this may differ by some definitions of the Hilbert Schmidt distance by a square-root.
Parameters
[in] a a density matrix
[in] b an equally-sized density matrix
Exceptions
exitWithError if either a or b are not density matrices, or if a and have mismatching dimensions.
Definition at line 892 of file QuEST.c.
References densmatr_calcHilbertSchmidtDistance(), validateDensityMatrQureg(), and validateMatchingQuregDims().
{
     validateDensityMatrQureg(a, __func__);
     validateDensityMatrQureg(b, __func__);
     validateMatchingQuregDims(a, b, __func__);
     return densmatr_calcHilbertSchmidtDistance(a, b);
 }
calcInnerProduct()
Complex calcInnerProduct (Qureg bra, Qureg ket)
Computes the inner product of two equal-size state vectors.
The same qureg may be passed as both bra and ket, though we recommend users check state-vector normalisation with calcTotalProb which employs Kahan summation for greater accuracy. Neither state-vector is modified.
Parameters
[in] bra qureg to be the 'bra' (i.e. have its values conjugate transposed) in the inner product
[in] ket qureg to be the 'ket' in the inner product
Returns
the complex inner product of bra and ket
Exceptions
exitWithError if either bra or ket are not state-vectors, or if bra and ket do not have equal dimensions.
Definition at line 840 of file QuEST.c.
References statevec_calcInnerProduct(), validateMatchingQuregDims(), and validateStateVecQureg().
{
     validateStateVecQureg(bra, __func__);
     validateStateVecQureg(ket, __func__);
     validateMatchingQuregDims(bra, ket,  __func__);
     return statevec_calcInnerProduct(bra, ket);
 }
calcProbOfOutcome()
qreal calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
This performs no actual measurement and does not change the state of the qubits.
Parameters
[in] qureg object representing the set of all qubits
[in] measureQubit qubit to study
[in] outcome for which to find the probability of the qubit being measured in
Returns
probability of qubit measureQubit being measured in the given outcome
Exceptions
exitWithError if measureQubit is outside [0, qureg.numQubitsRepresented), or if outcome is not in {0, 1}.
Definition at line 848 of file QuEST.c.
References densmatr_calcProbOfOutcome(), Qureg::isDensityMatrix, statevec_calcProbOfOutcome(), validateOutcome(), and validateTarget().
{
     validateTarget(qureg, measureQubit, __func__);
     validateOutcome(outcome, __func__);
     if (qureg.isDensityMatrix)
         return densmatr_calcProbOfOutcome(qureg, measureQubit, outcome);
     else
         return statevec_calcProbOfOutcome(qureg, measureQubit, outcome);
 }
calcPurity()
qreal calcPurity (Qureg qureg)
Calculates the purity of a density matrix, by the trace of the density matrix squared.
Returns . For a pure state, this =1. For a mixed state, the purity is less than 1 and is lower bounded by 1/2^n, where n is the number of qubits. The minimum purity is achieved for the maximally mixed state identity/2^n.
This function does not accept state-vectors, which clearly have purity 1.
Parameters
[in] qureg a density matrix of which to measure the purity
Returns
the purity
Exceptions
exitWithError if either combineQureg or otherQureg are not density matrices, or if the dimensions of combineQureg and otherQureg do not match, or if prob is not in [0, 1]
Definition at line 858 of file QuEST.c.
References densmatr_calcPurity(), and validateDensityMatrQureg().
{
     validateDensityMatrQureg(qureg, __func__);
     return densmatr_calcPurity(qureg);
 }
calcTotalProb()
qreal calcTotalProb (Qureg qureg)
A debugging function which calculates the probability of being in any state, which should always be 1.
For pure states, this is the norm of the entire state vector and for mixed states, is the trace of the density matrix. Note this calculation utilises Kahan summation for greaster accuracy, but is not parallelised and so will be slower than other functions.
Parameters
[in] qureg object representing a set of qubits
Returns
total probability
Definition at line 833 of file QuEST.c.
References densmatr_calcTotalProb(), Qureg::isDensityMatrix, and statevec_calcTotalProb().
{
     if (qureg.isDensityMatrix)
             return densmatr_calcTotalProb(qureg);
         else
             return statevec_calcTotalProb(qureg);
 }
clearRecordedQASM()
void clearRecordedQASM (Qureg qureg)
Clear all QASM so far recorded.
This does not start or stop recording
Definition at line 104 of file QuEST.c.
References qasm_clearRecorded().
{
     qasm_clearRecorded(qureg);
 }
cloneQureg()
void cloneQureg (Qureg targetQureg, Qureg copyQureg)
Set targetQureg to be a clone of copyQureg.
Registers must either both be state-vectors, or both be density matrices. Only the quantum state is cloned, auxilary info (like recorded QASM) is unchanged. copyQureg is unaffected.
Parameters
[in,out] targetQureg the qureg to have its quantum state overwritten
[in] copyQureg the qureg to have its quantum state cloned in targetQureg.
Definition at line 175 of file QuEST.c.
References statevec_cloneQureg(), validateMatchingQuregDims(), and validateMatchingQuregTypes().
{
     validateMatchingQuregTypes(targetQureg, copyQureg, __func__);
     validateMatchingQuregDims(targetQureg, copyQureg, __func__);
     statevec_cloneQureg(targetQureg, copyQureg);
 }
collapseToOutcome()
qreal collapseToOutcome (Qureg qureg, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
This is effectively performing a measurement and forcing the outcome. This is an irreversible change to the state vector, whereby incompatible states in the state vector are given zero amplitude and the remaining states are renormalised. Exits with error if the given outcome has ~zero probability, and so cannot be collapsed into.
Parameters
[in,out] qureg object representing the set of all qubits
[in] measureQubit qubit to measure
[in] outcome to force the measure qubit to enter
Returns
probability of the (forced) measurement outcome
Exceptions
exitWithError if measureQubit is outside [0, qureg.numQubitsRepresented), or if outcome is not in {0, 1}, or if the probability of outcome is zero (within machine epsilon)
Definition at line 735 of file QuEST.c.
References densmatr_calcProbOfOutcome(), densmatr_collapseToKnownProbOutcome(), Qureg::isDensityMatrix, qasm_recordMeasurement(), qreal, statevec_calcProbOfOutcome(), statevec_collapseToKnownProbOutcome(), validateMeasurementProb(), validateOutcome(), and validateTarget().
{
     validateTarget(qureg, measureQubit, __func__);
     validateOutcome(outcome, __func__);
     qreal outcomeProb;
     if (qureg.isDensityMatrix) {
         outcomeProb = densmatr_calcProbOfOutcome(qureg, measureQubit, outcome);
         validateMeasurementProb(outcomeProb, __func__);
         densmatr_collapseToKnownProbOutcome(qureg, measureQubit, outcome, outcomeProb);
     } else {
         outcomeProb = statevec_calcProbOfOutcome(qureg, measureQubit, outcome);
         validateMeasurementProb(outcomeProb, __func__);
         statevec_collapseToKnownProbOutcome(qureg, measureQubit, outcome, outcomeProb);
     }
     qasm_recordMeasurement(qureg, measureQubit);
     return outcomeProb;
 }
compactUnitary()
void compactUnitary (Qureg qureg, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
Given valid complex numbers and , applies the unitary
which is general up to a global phase factor. Valid , satisfy .
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented), or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 414 of file QuEST.c.
References getConjugateScalar(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordCompactUnitary(), statevec_compactUnitary(), validateTarget(), and validateUnitaryComplexPair().
{
     validateTarget(qureg, targetQubit, __func__);
     validateUnitaryComplexPair(alpha, beta, __func__);
     statevec_compactUnitary(qureg, targetQubit, alpha, beta);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_compactUnitary(qureg, targetQubit+shift, getConjugateScalar(alpha), getConjugateScalar(beta));
     }
     qasm_recordCompactUnitary(qureg, alpha, beta, targetQubit);
 }
compareStates()
int compareStates (Qureg mq1, Qureg mq2, qreal precision)
Return whether two given wavefunctions are equivalent within a given precision Global phase included in equivalence check.
For debugging purposes.
Definition at line 1047 of file QuEST.c.
References statevec_compareStates(), and validateMatchingQuregDims().
{
     validateMatchingQuregDims(qureg1, qureg2, __func__);
     return statevec_compareStates(qureg1, qureg2, precision);
 }
controlledCompactUnitary()
void controlledCompactUnitary (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
Given valid complex numbers and , applies the two-qubit unitary
to the control and target qubits. Valid , satisfy . The target unitary is general up to a global phase factor.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit apply the target unitary if this qubit has value 1
[in] targetQubit qubit on which to apply the target unitary
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal, or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 427 of file QuEST.c.
References getConjugateScalar(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledCompactUnitary(), statevec_controlledCompactUnitary(), validateControlTarget(), and validateUnitaryComplexPair().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     validateUnitaryComplexPair(alpha, beta, __func__);
     statevec_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledCompactUnitary(qureg,
             controlQubit+shift, targetQubit+shift,
             getConjugateScalar(alpha), getConjugateScalar(beta));
     }
     qasm_recordControlledCompactUnitary(qureg, alpha, beta, controlQubit, targetQubit);
 }
controlledMultiQubitUnitary()
void controlledMultiQubitUnitary (Qureg qureg, int ctrl, int * targs, const int numTargs, ComplexMatrixN u)
Apply a general controlled multi-qubit unitary (including a global phase factor).
One control and any number of target qubits can be specified. This effects the many-qubit unitary
on the control and target qubits.
The target qubits in targs are treated as ordered least sigifnicant to most significant in u.
The passed ComplexMatrix must be unitary and be a compatible size with the specified number of target qubits, otherwise an error is thrown.
Note that in distributed mode, this routine requires that each node contains at least 2^numTargs amplitudes. This means an q-qubit register (state vector or density matrix) can be distributed by at most 2^q / 2^numTargs nodes.
Parameters
[in,out] qureg object representing the set of all qubits
[in] ctrl the control qubit
[in] targs a list of the target qubits, ordered least to most significant
[in] numTargs the number of target qubits
[in] u unitary matrix to apply
Exceptions
exitWithError if ctrl or any index in targs is outside of [0, qureg.numQubitsRepresented), or if targs are not unique, or if targs contains ctrl, or if matrix u is not unitary, or if a node cannot fit the required number of target amplitudes in distributed mode.
Definition at line 324 of file QuEST.c.
References Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordComment(), setConjugateMatrixN(), shiftIndices(), statevec_controlledMultiQubitUnitary(), validateMultiControlsMultiTargets(), and validateMultiQubitUnitaryMatrix().
{
     validateMultiControlsMultiTargets(qureg, (int[]) {ctrl}, 1, targs, numTargs, __func__);
     validateMultiQubitUnitaryMatrix(qureg, u, numTargs, __func__);
     statevec_controlledMultiQubitUnitary(qureg, ctrl, targs, numTargs, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         shiftIndices(targs, numTargs, shift);
         setConjugateMatrixN(u);
         statevec_controlledMultiQubitUnitary(qureg, ctrl+shift, targs, numTargs, u);
         shiftIndices(targs, numTargs, -shift);
         setConjugateMatrixN(u);
     }
     qasm_recordComment(qureg, "Here, an undisclosed controlled multi-qubit unitary was applied.");
 }
controlledNot()
void controlledNot (Qureg qureg, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
This applies pauliX to the target qubit if the control qubit has value 1. This effects the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit nots the target if this qubit is 1
[in] targetQubit qubit to not
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented), or are equal.
Definition at line 534 of file QuEST.c.
References GATE_SIGMA_X, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledGate(), statevec_controlledNot(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledNot(qureg, controlQubit, targetQubit);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledNot(qureg, controlQubit+shift, targetQubit+shift);
     }
     qasm_recordControlledGate(qureg, GATE_SIGMA_X, controlQubit, targetQubit);
 }
controlledPauliY()
void controlledPauliY (Qureg qureg, const int controlQubit, const int targetQubit)
Apply the controlled pauliY (single control, single target) gate, also known as the c-Y and c-sigma-Y gate.
This applies pauliY to the target qubit if the control qubit has value 1. This effects the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit applies pauliY to the target if this qubit is 1
[in] targetQubit qubit to not
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented), or are equal.
Definition at line 546 of file QuEST.c.
References GATE_SIGMA_Y, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledGate(), statevec_controlledPauliY(), statevec_controlledPauliYConj(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledPauliY(qureg, controlQubit, targetQubit);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledPauliYConj(qureg, controlQubit+shift, targetQubit+shift);
     }
     qasm_recordControlledGate(qureg, GATE_SIGMA_Y, controlQubit, targetQubit);
 }
controlledPhaseFlip()
void controlledPhaseFlip (Qureg qureg, const int idQubit1, const int idQubit2)
Apply the (two-qubit) controlled phase flip gate, also known as the controlled pauliZ gate.
For each state, if both input qubits have value one, multiply the amplitude of that state by -1. This applies the two-qubit unitary:
Parameters
[in,out] qureg object representing the set of all qubits
[in] idQubit1,idQubit2 qubits to operate upon
Exceptions
exitWithError if idQubit1 or idQubit2 are outside [0, qureg.numQubitsRepresented), or are equal
Definition at line 558 of file QuEST.c.
References GATE_SIGMA_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledGate(), statevec_controlledPhaseFlip(), and validateControlTarget().
{
     validateControlTarget(qureg, idQubit1, idQubit2, __func__);
     statevec_controlledPhaseFlip(qureg, idQubit1, idQubit2);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledPhaseFlip(qureg, idQubit1+shift, idQubit2+shift);
     }
     qasm_recordControlledGate(qureg, GATE_SIGMA_Z, idQubit1, idQubit2);
 }
controlledPhaseShift()
void controlledPhaseShift (Qureg qureg, const int idQubit1, const int idQubit2, qreal angle)
Introduce a phase factor on state of qubits idQubit1 and idQubit2.
For angle , this effects the unitary
on idQubit1 and idQubit2.
Parameters
[in,out] qureg object representing the set of all qubits
[in] idQubit1 first qubit in the state to phase shift
[in] idQubit2 second qubit in the state to phase shift
[in] angle amount by which to shift the phase in radians
Exceptions
exitWithError if idQubit1 or idQubit2 are outside [0, qureg.numQubitsRepresented), or are equal
Definition at line 508 of file QuEST.c.
References GATE_PHASE_SHIFT, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledParamGate(), statevec_controlledPhaseShift(), and validateControlTarget().
{
     validateControlTarget(qureg, idQubit1, idQubit2, __func__);
     statevec_controlledPhaseShift(qureg, idQubit1, idQubit2, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledPhaseShift(qureg, idQubit1+shift, idQubit2+shift, -angle);
     }
     qasm_recordControlledParamGate(qureg, GATE_PHASE_SHIFT, idQubit1, idQubit2, angle);
 }
controlledRotateAroundAxis()
void controlledRotateAroundAxis (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle, Vector axis)
Applies a controlled rotation by a given angle around a given vector on the Bloch-sphere.
The vector must not be zero (else an error is thrown), but needn't be unit magnitude.
For angle and axis vector , applies to states where the target qubit is 1 (is the vector of Pauli matrices).
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit qubit with value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate in radians
[in] axis vector around which to rotate (can be non-unit; will be normalised)
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal or if axis is the zero vector
Definition at line 597 of file QuEST.c.
References Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledAxisRotation(), statevec_controlledRotateAroundAxis(), statevec_controlledRotateAroundAxisConj(), validateControlTarget(), and validateVector().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     validateVector(axis, __func__);
     statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, axis);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledRotateAroundAxisConj(qureg, controlQubit+shift, targetQubit+shift, angle, axis);
     }
     qasm_recordControlledAxisRotation(qureg, angle, axis, controlQubit, targetQubit);
 }
controlledRotateX()
void controlledRotateX (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the X-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal.
Definition at line 231 of file QuEST.c.
References GATE_ROTATE_X, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledParamGate(), statevec_controlledRotateX(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledRotateX(qureg, controlQubit, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledRotateX(qureg, controlQubit+shift, targetQubit+shift, -angle);
     }
     qasm_recordControlledParamGate(qureg, GATE_ROTATE_X, controlQubit, targetQubit, angle);
 }
controlledRotateY()
void controlledRotateY (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the Y-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal.
Definition at line 243 of file QuEST.c.
References GATE_ROTATE_Y, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledParamGate(), statevec_controlledRotateY(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledRotateY(qureg, controlQubit, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledRotateY(qureg, controlQubit+shift, targetQubit+shift, angle); // rotateY is real
     }
     qasm_recordControlledParamGate(qureg, GATE_ROTATE_Y, controlQubit, targetQubit, angle);
 }
controlledRotateZ()
void controlledRotateZ (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the Z-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal.
Definition at line 255 of file QuEST.c.
References GATE_ROTATE_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledParamGate(), statevec_controlledRotateZ(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledRotateZ(qureg, controlQubit, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledRotateZ(qureg, controlQubit+shift, targetQubit+shift, -angle);
     }
     qasm_recordControlledParamGate(qureg, GATE_ROTATE_Z, controlQubit, targetQubit, angle);
 }
controlledTwoQubitUnitary()
void controlledTwoQubitUnitary (Qureg qureg, const int controlQubit, const int targetQubit1, const int targetQubit2, ComplexMatrix4 u)
Apply a general controlled two-qubit unitary (including a global phase factor).
The given unitary is applied to the target amplitudes where the control qubit has value 1. This effects the many-qubit unitary
on the control and target qubits.
targetQubit1 is treated as the least significant qubit in u, such that a row in u is dotted with the vector
The passed 4x4 ComplexMatrix must be unitary, otherwise an error is thrown.
Note that in distributed mode, this routine requires that each node contains at least 4 amplitudes. This means an q-qubit register (state vector or density matrix) can be distributed by at most 2^q/4 nodes.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit the control qubit which must be in state 1 to effect the given unitary
[in] targetQubit1 first qubit to operate on, treated as least significant in u
[in] targetQubit2 second qubit to operate on, treated as most significant in u
[in] u unitary matrix to apply
Exceptions
exitWithError if controlQubit, targetQubit1 or targetQubit2 are outside [0, qureg.numQubitsRepresented), or if any of controlQubit, targetQubit1 and targetQubit2 are equal, or matrix u is not unitary, or if each node cannot fit 4 amplitudes in distributed mode.
Definition at line 280 of file QuEST.c.
References getConjugateMatrix4(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordComment(), statevec_controlledTwoQubitUnitary(), validateMultiControlsMultiTargets(), and validateTwoQubitUnitaryMatrix().
{
     validateMultiControlsMultiTargets(qureg, (int[]) {controlQubit}, 1, (int[]) {targetQubit1, targetQubit2}, 2, __func__);
     validateTwoQubitUnitaryMatrix(qureg, u, __func__);
     statevec_controlledTwoQubitUnitary(qureg, controlQubit, targetQubit1, targetQubit2, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledTwoQubitUnitary(qureg, controlQubit+shift, targetQubit1+shift, targetQubit2+shift, getConjugateMatrix4(u));
     }
     qasm_recordComment(qureg, "Here, an undisclosed controlled 2-qubit unitary was applied.");
 }
controlledUnitary()
void controlledUnitary (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
The given unitary is applied to the target qubit if the control qubit has value 1, effecting the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit apply unitary if this qubit is 1
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal, or if u is not unitary.
Definition at line 371 of file QuEST.c.
References getConjugateMatrix2(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledUnitary(), statevec_controlledUnitary(), validateControlTarget(), and validateOneQubitUnitaryMatrix().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     validateOneQubitUnitaryMatrix(u, __func__);
     statevec_controlledUnitary(qureg, controlQubit, targetQubit, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledUnitary(qureg, controlQubit+shift, targetQubit+shift, getConjugateMatrix2(u));
     }
     qasm_recordControlledUnitary(qureg, u, controlQubit, targetQubit);
 }
createCloneQureg()
Qureg createCloneQureg (Qureg qureg, QuESTEnv env)
Create a new Qureg which is an exact clone of the passed qureg, which can be either a statevector or a density matrix.
That is, it will have the same dimensions as the passed qureg and begin in an identical quantum state. This must be destroyed by the user later with destroyQureg
Returns
an object representing the set of qubits
Parameters
[in] qureg an existing qureg to be cloned
[in] env object representing the execution environment (local, multinode etc)
Definition at line 73 of file QuEST.c.
References Qureg::isDensityMatrix, Qureg::numQubitsInStateVec, Qureg::numQubitsRepresented, qasm_setup(), statevec_cloneQureg(), and statevec_createQureg().
{
     Qureg newQureg;
     statevec_createQureg(&newQureg, qureg.numQubitsInStateVec, env);
     newQureg.isDensityMatrix = qureg.isDensityMatrix;
     newQureg.numQubitsRepresented = qureg.numQubitsRepresented;
     newQureg.numQubitsInStateVec = qureg.numQubitsInStateVec;
     qasm_setup(&newQureg);
     statevec_cloneQureg(newQureg, qureg);
     return newQureg;
 }
createComplexMatrixN()
ComplexMatrixN createComplexMatrixN (int numQubits)
Create (dynamically) a square complex matrix which can be passed to the multi-qubit general unitary functions.
The matrix will have dimensions (2^numQubits) by (2^numQubits), and all elements of .real and .imag are initialised to zero. The ComplexMatrixN must eventually be freed using destroyComplexMatrixN(). Like ComplexMatrix2 and ComplexMatrix4, the returned ComplexMatrixN is safe to return from functions.
One can instead use getStaticComplexMatrixN() to create a ComplexMatrixN struct in the stack (which doesn't need to be explicitly freed).
Parameters
[in] numQubits the number of qubits of which the returned ComplexMatrixN will correspond
Returns
a dynamic ComplexMatrixN struct, that is one where the .real and .imag fields are arrays kept in the heap and must be freed.
Definition at line 1003 of file QuEST.c.
References ComplexMatrixN::imag, ComplexMatrixN::numQubits, ComplexMatrixN::real, and validateCreateNumQubits().
{
      validateCreateNumQubits(numQubits, __func__);
      int numRows = 1 << numQubits;
      ComplexMatrixN m = {
          .numQubits = numQubits,
          .real = malloc(numRows * sizeof *m.real),
          .imag = malloc(numRows * sizeof *m.imag)};
      for (int n=0; n < 1<<numQubits; n++) {
          m.real[n] = calloc(numRows, sizeof **m.real);
          m.imag[n] = calloc(numRows, sizeof **m.imag);
      }
      return m;
  }
createDensityQureg()
Qureg createDensityQureg (int numQubits, QuESTEnv env)
Create a Qureg for qubits which are represented by a density matrix, and can be in mixed states.
Allocates space for a density matrix of probability amplitudes, including space for temporary values to be copied from one other chunk if running the distributed version. Define properties related to the size of the set of qubits. initZeroState is automatically called allocation, so that the density qureg begins in the zero state |0><0|.
Returns
an object representing the set of qubits
Parameters
[in] numQubits number of qubits in the system
[in] env object representing the execution environment (local, multinode etc)
Exceptions
exitWithError if numQubits <= 0
Definition at line 59 of file QuEST.c.
References initZeroState(), Qureg::isDensityMatrix, Qureg::numQubitsInStateVec, Qureg::numQubitsRepresented, qasm_setup(), statevec_createQureg(), and validateCreateNumQubits().
{
     validateCreateNumQubits(numQubits, __func__);
     Qureg qureg;
     statevec_createQureg(&qureg, 2*numQubits, env);
     qureg.isDensityMatrix = 1;
     qureg.numQubitsRepresented = numQubits;
     qureg.numQubitsInStateVec = 2*numQubits;
     qasm_setup(&qureg);
     initZeroState(qureg); // safe call to public function
     return qureg;
 }
createQureg()
Qureg createQureg (int numQubits, QuESTEnv env)
Create a Qureg object representing a set of qubits which will remain in a pure state.
Allocate space for state vector of probability amplitudes, including space for temporary values to be copied from one other chunk if running the distributed version. Define properties related to the size of the set of qubits. The qubits are initialised in the zero state (i.e. initZeroState is automatically called)
Returns
an object representing the set of qubits
Parameters
[in] numQubits number of qubits in the system
[in] env object representing the execution environment (local, multinode etc)
Exceptions
exitWithError if numQubits <= 0
Definition at line 45 of file QuEST.c.
References initZeroState(), Qureg::isDensityMatrix, Qureg::numQubitsInStateVec, Qureg::numQubitsRepresented, qasm_setup(), statevec_createQureg(), and validateCreateNumQubits().
{
     validateCreateNumQubits(numQubits, __func__);
     Qureg qureg;
     statevec_createQureg(&qureg, numQubits, env);
     qureg.isDensityMatrix = 0;
     qureg.numQubitsRepresented = numQubits;
     qureg.numQubitsInStateVec = numQubits;
     qasm_setup(&qureg);
     initZeroState(qureg); // safe call to public function
     return qureg;
 }
destroyComplexMatrixN()
void destroyComplexMatrixN (ComplexMatrixN matr)
Destroy a ComplexMatrixN instance created with createComplexMatrixN()
It is invalid to attempt to destroy a matrix created with getStaticComplexMatrixN().
Parameters
[in] matr the dynamic matrix (created with createComplexMatrixN()) to deallocate
Exceptions
exitWithError if matr was not yet allocated.
malloc_error if matr was static (created with getStaticComplexMatrixN())
Definition at line 1020 of file QuEST.c.
References ComplexMatrixN::imag, ComplexMatrixN::numQubits, ComplexMatrixN::real, and validateMatrixInit().
{
     validateMatrixInit(m, __func__);
     int numRows = 1 << m.numQubits;
     for (int r=0; r < numRows; r++) {
         free(m.real[r]);
         free(m.imag[r]);
     }
     free(m.real);
     free(m.imag);
 }
destroyQureg()
void destroyQureg (Qureg qureg, QuESTEnv env)
Deallocate a Qureg object representing a set of qubits.
Free memory allocated to state vector of probability amplitudes, including temporary vector for values copied from another chunk if running the distributed version.
Parameters
[in,out] qureg object to be deallocated
[in] env object representing the execution environment (local, multinode etc)
Definition at line 86 of file QuEST.c.
References qasm_free(), and statevec_destroyQureg().
{
     statevec_destroyQureg(qureg, env);
     qasm_free(qureg);
 }
getAmp()
Complex getAmp (Qureg qureg, long long int index)
Get the complex amplitude at a given index in the state vector.
Parameters
[in] qureg object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
amplitude at index, returned as a Complex struct (with .real and .imag attributes)
Exceptions
exitWithError if index is outside [0,) where qureg.numQubitsRepresented
Definition at line 708 of file QuEST.c.
References Complex::imag, Complex::real, statevec_getImagAmp(), statevec_getRealAmp(), validateStateIndex(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateStateIndex(qureg, index, __func__);
     Complex amp;
     amp.real = statevec_getRealAmp(qureg, index);
     amp.imag = statevec_getImagAmp(qureg, index);
     return amp;
 }
getDensityAmp()
Complex getDensityAmp (Qureg qureg, long long int row, long long int col)
Get an amplitude from a density matrix at a given row and column.
Parameters
[in] qureg object representing a density matrix
[in] row row of the desired amplitude in the density matrix
[in] col column of the desired amplitude in the density matrix
Returns
a Complex scalar representing the desired amplitude
Exceptions
exitWithError if qureg is a statevector, or if row or col are outside [0,) where qureg.numQubitsRepresented
Definition at line 718 of file QuEST.c.
References Qureg::numQubitsRepresented, Complex::real, statevec_getImagAmp(), statevec_getRealAmp(), validateDensityMatrQureg(), and validateStateIndex().
{
     validateDensityMatrQureg(qureg, __func__);
     validateStateIndex(qureg, row, __func__);
     validateStateIndex(qureg, col, __func__);
     long long ind = row + col*(1LL << qureg.numQubitsRepresented);
     Complex amp;
     amp.real = statevec_getRealAmp(qureg, ind);
     amp.imag = statevec_getImagAmp(qureg, ind);
     return amp;
 }
getImagAmp()
qreal getImagAmp (Qureg qureg, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters
[in] qureg object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
imaginary component at that index
Exceptions
exitWithError if index is outside [0,) where qureg.numQubitsRepresented
Definition at line 694 of file QuEST.c.
References statevec_getImagAmp(), validateStateIndex(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateStateIndex(qureg, index, __func__);
     return statevec_getImagAmp(qureg, index);
 }
getNumAmps()
long long int getNumAmps (Qureg qureg)
Get the number of probability amplitudes in a qureg object, given by 2^numQubits.
Definition at line 681 of file QuEST.c.
References Qureg::numAmpsTotal, and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     return qureg.numAmpsTotal;
 }
getNumQubits()
int getNumQubits (Qureg qureg)
Get the number of qubits in a qureg object.
Definition at line 677 of file QuEST.c.
References Qureg::numQubitsRepresented.
{
     return qureg.numQubitsRepresented;
 }
getProbAmp()
qreal getProbAmp (Qureg qureg, long long int index)
Get the probability of the state at an index in the full state vector.
Parameters
[in] qureg object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
realEl*realEl + imagEl*imagEl
Exceptions
exitWithError if index is outside [0,) where qureg.numQubitsRepresented
Definition at line 701 of file QuEST.c.
References statevec_getProbAmp(), validateStateIndex(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateStateIndex(qureg, index, __func__);
     return statevec_getProbAmp(qureg, index);
 }
getQuEST_PREC()
int getQuEST_PREC (void)
Definition at line 1072 of file QuEST.c.
References qreal.
{
   return sizeof(qreal)/4;
 }
getRealAmp()
qreal getRealAmp (Qureg qureg, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters
[in] qureg object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
real component at that index
Exceptions
exitWithError if index is outside [0,) where qureg.numQubitsRepresented
Definition at line 687 of file QuEST.c.
References statevec_getRealAmp(), validateStateIndex(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateStateIndex(qureg, index, __func__);
     return statevec_getRealAmp(qureg, index);
 }
hadamard()
void hadamard (Qureg qureg, const int targetQubit)
Apply the single-qubit Hadamard gate.
This takes to and to , and is equivalent to a rotation of around the x-axis then about the y-axis on the Bloch-sphere. I.e.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 187 of file QuEST.c.
References GATE_HADAMARD, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_hadamard(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_hadamard(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_hadamard(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_HADAMARD, targetQubit);
 }
initBlankState()
void initBlankState (Qureg qureg)
Initialises a qureg to have all-zero-amplitudes.
This is an unphysical state useful for iteratively building a state with e.g. setWeightedQureg, and should not be confused with the zero state |0...0>
Parameters
[in,out] qureg the object representing the set of all qubits to initialise
Definition at line 128 of file QuEST.c.
References qasm_recordComment(), and statevec_initBlankState().
{
     statevec_initBlankState(qureg);
     qasm_recordComment(qureg, "Here, the register was initialised to an unphysical all-zero-amplitudes 'state'.");
 }
initClassicalState()
void initClassicalState (Qureg qureg, long long int stateInd)
Initialise a set of qubits to the classical state with index stateInd.
Note has stateInd 0, has stateInd 1, has stateInd , etc. Subsequent calls to getProbAmp will yield 0 for all indices except stateInd.
Parameters
[in,out] qureg the object representing the set of qubits to be initialised
[in] stateInd the index (0 to the number of amplitudes, exclusive) of the state to give probability 1
Definition at line 143 of file QuEST.c.
References densmatr_initClassicalState(), Qureg::isDensityMatrix, qasm_recordInitClassical(), statevec_initClassicalState(), and validateStateIndex().
{
     validateStateIndex(qureg, stateInd, __func__);
     if (qureg.isDensityMatrix)
         densmatr_initClassicalState(qureg, stateInd);
     else
         statevec_initClassicalState(qureg, stateInd);
     qasm_recordInitClassical(qureg, stateInd);
 }
initComplexMatrixN()
void initComplexMatrixN (ComplexMatrixN m, qreal real[][1<< m.numQubits], qreal imag[][1<< m.numQubits])
Initialises a ComplexMatrixN instance to have the passed real and imag values.
This allows succint population of any-sized ComplexMatrixN, e.g. through 2D arrays:
ComplexMatrixN m = createComplexMatrixN(3);
initComplexMatrixN(m,
    (qreal[8][8]) {{1,2,3,4,5,6,7,8}, {0}},
    (qreal[8][8]) {{0}});
m can be created by either createComplexMatrixN() or getStaticComplexMatrixN().
This function is only callable in C, since C++ signatures cannot contain variable-length 2D arrays
Parameters
[in] m the matrix to initialise
[in] real matrix of real values; can be 2D array of array of pointers
[in] imag matrix of imaginary values; can be 2D array of array of pointers
Exceptions
exitWithError if m has not been allocated (e.g. with createComplexMatrixN())
Definition at line 1032 of file QuEST.c.
References ComplexMatrixN::imag, ComplexMatrixN::numQubits, ComplexMatrixN::real, and validateMatrixInit().
{
     validateMatrixInit(m, __func__);
     int dim = 1 << m.numQubits;
     for (int i=0; i<dim; i++)
         for (int j=0; j<dim; j++) {
             m.real[i][j] = re[i][j];
             m.imag[i][j] = im[i][j];
         }
 }
initPlusState()
void initPlusState (Qureg qureg)
Initialise a set of qubits to the plus state .
This is the product state of qubits where every classical state is uniformly populated with real coefficient . This is equivalent to applying a Hadamard to every qubit in the zero state:
Parameters
[in,out] qureg the object representing the set of qubits to be initialised
Definition at line 134 of file QuEST.c.
References densmatr_initPlusState(), Qureg::isDensityMatrix, qasm_recordInitPlus(), and statevec_initPlusState().
{
     if (qureg.isDensityMatrix)
         densmatr_initPlusState(qureg);
     else
         statevec_initPlusState(qureg);
     qasm_recordInitPlus(qureg);
 }
initPureState()
void initPureState (Qureg qureg, Qureg pure)
Initialise a set of qubits, which can be a state vector or density matrix, to a given pure state.
If qureg is a state-vector, this merely makes qureg an identical copy of pure. If qureg is a density matrix, this makes qureg 100% likely to be in the pure state.
Parameters
[in,out] qureg the object representing the set of qubits to be initialised
[in] pure the pure state to be copied or to give probability 1 in qureg
Definition at line 155 of file QuEST.c.
References densmatr_initPureState(), Qureg::isDensityMatrix, qasm_recordComment(), statevec_cloneQureg(), validateMatchingQuregDims(), and validateSecondQuregStateVec().
{
     validateSecondQuregStateVec(pure, __func__);
     validateMatchingQuregDims(qureg, pure, __func__);
     if (qureg.isDensityMatrix)
         densmatr_initPureState(qureg, pure);
     else
         statevec_cloneQureg(qureg, pure);
     qasm_recordComment(qureg, "Here, the register was initialised to an undisclosed given pure state.");
 }
initStateDebug()
void initStateDebug (Qureg qureg)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
For debugging processes
Parameters
[in,out] qureg object representing the set of qubits to be initialised
Definition at line 1052 of file QuEST.c.
References statevec_initStateDebug().
{
     statevec_initStateDebug(qureg);
 }
initStateFromAmps()
void initStateFromAmps (Qureg qureg, qreal * reals, qreal * imags)
Initialise qureg by specifying the complete statevector.
The real and imaginary components of the amplitudes are passed in separate arrays, each of which must have length qureg.numAmpsTotal. There is no automatic checking that the passed arrays are L2 normalised.
Parameters
[in,out] qureg the object representing the set of qubits to be initialised
[in] reals array of the real components of the new amplitudes
[in] imags array of the imaginary components of the new amplitudes
Exceptions
exitWithError if qureg is not a statevector (i.e. is a density matrix)
Definition at line 167 of file QuEST.c.
References Qureg::numAmpsTotal, qasm_recordComment(), statevec_setAmps(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     statevec_setAmps(qureg, 0, reals, imags, qureg.numAmpsTotal);
     qasm_recordComment(qureg, "Here, the register was initialised to an undisclosed given pure state.");
 }
initStateFromSingleFile()
void initStateFromSingleFile (Qureg * qureg, char filename[200], QuESTEnv env)
Initialises the wavefunction amplitudes according to those specified in a file.
For debugging purpsoses
Definition at line 1056 of file QuEST.c.
References statevec_initStateFromSingleFile(), and validateFileOpened().
{
     int success = statevec_initStateFromSingleFile(qureg, filename, env);
     validateFileOpened(success, __func__);
 }
initStateOfSingleQubit()
void initStateOfSingleQubit (Qureg * qureg, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
Parameters
[in,out] qureg object representing the set of qubits to be initialised
[in] qubitId id of qubit to set to state 'outcome'
[in] outcome value of qubit 'qubitId' to set
Definition at line 1061 of file QuEST.c.
References statevec_initStateOfSingleQubit(), validateOutcome(), validateStateVecQureg(), and validateTarget().
{
     validateStateVecQureg(*qureg, __func__);
     validateTarget(*qureg, qubitId, __func__);
     validateOutcome(outcome, __func__);
     statevec_initStateOfSingleQubit(qureg, qubitId, outcome);
 }
initZeroState()
void initZeroState (Qureg qureg)
Initialise a set of qubits to the classical zero state .
Parameters
[in,out] qureg the object representing the set of all qubits to initialise
Definition at line 122 of file QuEST.c.
References qasm_recordInitZero(), and statevec_initZeroState().
Referenced by createDensityQureg(), and createQureg().
{
     statevec_initZeroState(qureg); // valid for both statevec and density matrices
     qasm_recordInitZero(qureg);
 }
measure()
int measure (Qureg qureg, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters
[in,out] qureg object representing the set of all qubits
[in] measureQubit qubit to measure
Returns
the measurement outcome, 0 or 1
Exceptions
exitWithError if measureQubit is outside [0, qureg.numQubitsRepresented)
Definition at line 767 of file QuEST.c.
References densmatr_measureWithStats(), Qureg::isDensityMatrix, qasm_recordMeasurement(), qreal, statevec_measureWithStats(), and validateTarget().
{
     validateTarget(qureg, measureQubit, __func__);
     int outcome;
     qreal discardedProb;
     if (qureg.isDensityMatrix)
         outcome = densmatr_measureWithStats(qureg, measureQubit, &discardedProb);
     else
         outcome = statevec_measureWithStats(qureg, measureQubit, &discardedProb);
     qasm_recordMeasurement(qureg, measureQubit);
     return outcome;
 }
measureWithStats()
int measureWithStats (Qureg qureg, int measureQubit, qreal * outcomeProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters
[in,out] qureg object representing the set of all qubits
[in] measureQubit qubit to measure
[out] outcomeProb a pointer to a qreal which is set to the probability of the occurred outcome
Returns
the measurement outcome, 0 or 1
Exceptions
exitWithError if measureQubit is outside [0, qureg.numQubitsRepresented)
Definition at line 754 of file QuEST.c.
References densmatr_measureWithStats(), Qureg::isDensityMatrix, qasm_recordMeasurement(), statevec_measureWithStats(), and validateTarget().
{
     validateTarget(qureg, measureQubit, __func__);
     int outcome;
     if (qureg.isDensityMatrix)
         outcome = densmatr_measureWithStats(qureg, measureQubit, outcomeProb);
     else
         outcome = statevec_measureWithStats(qureg, measureQubit, outcomeProb);
     qasm_recordMeasurement(qureg, measureQubit);
     return outcome;
 }
mixDamping()
void mixDamping (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit damping (decay to 0 state).
With probability prob, applies damping (transition from 1 to 0 state).
This transforms qureg = into the mixed state
where q = targetQubit. prob cannot exceed 1, at which total damping/decay occurs.
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit upon which to induce depolarising noise
[in] prob the probability of the depolarising error occuring
Exceptions
exitWithError if qureg is not a density matrix, or if targetQubit is outside [0, qureg.numQubitsRepresented), or if prob is not in [0, 1]
Definition at line 938 of file QuEST.c.
References densmatr_mixDamping(), validateDensityMatrQureg(), validateOneQubitDampingProb(), and validateTarget().
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, targetQubit, __func__);
     validateOneQubitDampingProb(prob, __func__);
     densmatr_mixDamping(qureg, targetQubit, prob);
 }
mixDensityMatrix()
void mixDensityMatrix (Qureg combineQureg, qreal prob, Qureg otherQureg)
Modifies combineQureg to become (1-prob)combineProb + prob otherQureg.
Both registers must be equal-dimension density matrices, and prob must be in [0, 1].
Parameters
[in,out] combineQureg a density matrix to be modified
[in] prob the probability of otherQureg in the modified combineQureg
[in] otherQureg a density matrix to be mixed into combineQureg
Exceptions
exitWithError if either combineQureg or otherQureg are not density matrices, or if the dimensions of combineQureg and otherQureg do not match, or if prob is not in [0, 1]
Definition at line 781 of file QuEST.c.
References densmatr_mixDensityMatrix(), validateDensityMatrQureg(), validateMatchingQuregDims(), and validateProb().
{
     validateDensityMatrQureg(combineQureg, __func__);
     validateDensityMatrQureg(otherQureg, __func__);
     validateMatchingQuregDims(combineQureg, otherQureg, __func__);
     validateProb(otherProb, __func__);
     densmatr_mixDensityMatrix(combineQureg, otherProb, otherQureg);
 }
mixDephasing()
void mixDephasing (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit dephasing noise.
With probability prob, applies Pauli Z to targetQubit.
This transforms qureg = into the mixed state
where q = targetQubit. prob cannot exceed 1/2, which maximally mixes targetQubit.
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit upon which to induce dephasing noise
[in] prob the probability of the phase error occuring
Exceptions
exitWithError if qureg is not a density matrix, or if targetQubit is outside [0, qureg.numQubitsRepresented), or if prob is not in [0, 1/2]
Definition at line 905 of file QuEST.c.
References densmatr_mixDephasing(), qasm_recordComment(), validateDensityMatrQureg(), validateOneQubitDephaseProb(), and validateTarget().
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, targetQubit, __func__);
     validateOneQubitDephaseProb(prob, __func__);
     densmatr_mixDephasing(qureg, targetQubit, 2*prob);
     qasm_recordComment(qureg,
         "Here, a phase (Z) error occured on qubit %d with probability %g", targetQubit, prob);
 }
mixDepolarising()
void mixDepolarising (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit homogeneous depolarising noise.
With probability prob, applies (uniformly) either Pauli X, Y, or Z to targetQubit.
This transforms qureg = into the mixed state
where q = targetQubit. prob cannot exceed 3/4, at which maximal mixing occurs.
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit upon which to induce depolarising noise
[in] prob the probability of the depolarising error occuring
Exceptions
exitWithError if qureg is not a density matrix, or if targetQubit is outside [0, qureg.numQubitsRepresented), or if prob is not in [0, 3/4]
Definition at line 927 of file QuEST.c.
References densmatr_mixDepolarising(), qasm_recordComment(), validateDensityMatrQureg(), validateOneQubitDepolProb(), and validateTarget().
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, targetQubit, __func__);
     validateOneQubitDepolProb(prob, __func__);
     densmatr_mixDepolarising(qureg, targetQubit, (4*prob)/3.0);
     qasm_recordComment(qureg,
         "Here, a homogeneous depolarising error (X, Y, or Z) occured on "
         "qubit %d with total probability %g", targetQubit, prob);
 }
mixKrausMap()
void mixKrausMap (Qureg qureg, int target, ComplexMatrix2 * ops, int numOps)
Apply a general single-qubit Kraus map to a density matrix, as specified by at most four Kraus operators.
A Kraus map is also referred to as a "operator-sum representation" of a quantum channel. This allows one to simulate a general single-qubit noise process.
The Kraus map must be completely positive and trace preserving, which constrains each in ops by
where is the identity matrix.
Note that in distributed mode, this routine requires that each node contains at least 4 amplitudes. This means an q-qubit register can be distributed by at most 2^(q-2) numTargs nodes.
Parameters
[in,out] qureg the density matrix to which to apply the map
[in] target the target qubit of the map
[in] ops an array of at most 4 Kraus operators
[in] numOps the number of operators in ops which must be >0 and <= 4.
Exceptions
exitWithError if qureg is not a density matrix, or if target is outside of [0, qureg.numQubitsRepresented), or if numOps is outside [1, 4], or if ops do not create a completely positive, trace preserving map, or if a node cannot fit 4 amplitudes in distributed mode.
Definition at line 969 of file QuEST.c.
References densmatr_mixKrausMap(), qasm_recordComment(), validateDensityMatrQureg(), validateOneQubitKrausMap(), and validateTarget().
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, target, __func__);
     validateOneQubitKrausMap(qureg, ops, numOps, __func__);
     densmatr_mixKrausMap(qureg, target, ops, numOps);
     qasm_recordComment(qureg,
         "Here, an undisclosed Kraus map was effected on qubit %d", target);
 }
mixMultiQubitKrausMap()
void mixMultiQubitKrausMap (Qureg qureg, int * targets, int numTargets, ComplexMatrixN * ops, int numOps)
Apply a general N-qubit Kraus map to a density matrix, as specified by at most (2N)^2 Kraus operators.
A Kraus map is also referred to as a "operator-sum representation" of a quantum channel. This allows one to simulate a general two-qubit noise process.
The Kraus map must be completely positive and trace preserving, which constrains each in ops by
where is the identity matrix.
The first qubit in targets is treated as the least significant qubit in each op in ops.
Note that in distributed mode, this routine requires that each node contains at least (2N)^2 amplitudes. This means an q-qubit register can be distributed by at most 2^(q-2)/N^2 nodes.
Parameters
[in,out] qureg the density matrix to which to apply the map
[in] targets a list of target qubit indices, the first of which is treated as least significant in each op in ops
[in] numTargets the length of targets
[in] ops an array of at most (2N)^2 Kraus operators
[in] numOps the number of operators in ops which must be >0 and <= (2N)^2.
Exceptions
exitWithError if qureg is not a density matrix, or if any target in targets is outside of [0, qureg.numQubitsRepresented), or if any qubit in targets is repeated, or if numOps is outside [1, (2 numTargets)^2], or if any ComplexMatrixN in does not have op.numQubits == numTargets, or if ops do not create a completely positive, trace preserving map, or if a node cannot fit (2N)^2 amplitudes in distributed mode.
Definition at line 989 of file QuEST.c.
References densmatr_mixMultiQubitKrausMap(), qasm_recordComment(), validateDensityMatrQureg(), validateMultiQubitKrausMap(), and validateMultiTargets().
{
     validateDensityMatrQureg(qureg, __func__);
     validateMultiTargets(qureg, targets, numTargets, __func__);
     validateMultiQubitKrausMap(qureg, numTargets, ops, numOps, __func__);
     densmatr_mixMultiQubitKrausMap(qureg, targets, numTargets, ops, numOps);
     qasm_recordComment(qureg,
         "Here, an undisclosed %d-qubit Kraus map was applied to undisclosed qubits", numTargets);
 }
mixPauli()
void mixPauli (Qureg qureg, int targetQubit, qreal probX, qreal probY, qreal probZ)
Mixes a density matrix qureg to induce general single-qubit Pauli noise.
With probabilities probX, probY and probZ, applies Pauli X, Y, and Z respectively to targetQubit.
This transforms qureg = into the mixed state
where q = targetQubit. Each of probX, probY and probZ cannot exceed the chance of no error: 1 - probX - probY - probZ
This function operates by first converting the given Pauli probabilities into a single-qubit Kraus map (four 2x2 operators).
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit to decohere
[in] probX the probability of inducing an X error
[in] probX the probability of inducing an Y error
[in] probX the probability of inducing an Z error
Exceptions
exitWithError if qureg is not a density matrix, or if targetQubit is outside [0, qureg.numQubitsRepresented), or if any of probX, probY or probZ are not in [0, 1], or if any of p in {probX, probY or probZ} don't satisfy p <= (1 - probX - probY - probZ)
Definition at line 958 of file QuEST.c.
References densmatr_mixPauli(), qasm_recordComment(), validateDensityMatrQureg(), validateOneQubitPauliProbs(), and validateTarget().
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, qubit, __func__);
     validateOneQubitPauliProbs(probX, probY, probZ, __func__);
     densmatr_mixPauli(qureg, qubit, probX, probY, probZ);
     qasm_recordComment(qureg,
         "Here, X, Y and Z errors occured on qubit %d with probabilities "
         "%g, %g and %g respectively", qubit, probX, probY, probZ);
 }
mixTwoQubitDephasing()
void mixTwoQubitDephasing (Qureg qureg, int qubit1, int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit dephasing noise.
With probability prob, applies Pauli Z to either or both qubits.
This transforms qureg = into the mixed state
where a = qubit1, b = qubit2. prob cannot exceed 3/4, at which maximal mixing occurs.
Parameters
[in,out] qureg a density matrix
[in] qubit1 qubit upon which to induce dephasing noise
[in] qubit2 qubit upon which to induce dephasing noise
[in] prob the probability of the phase error occuring
Exceptions
exitWithError if qureg is not a density matrix, or if either qubit1 or qubit2 is outside [0, qureg.numQubitsRepresented), or if qubit1 = qubit2, or if prob is not in [0, 3/4]
Definition at line 915 of file QuEST.c.
References densmatr_mixTwoQubitDephasing(), ensureIndsIncrease(), qasm_recordComment(), validateDensityMatrQureg(), validateTwoQubitDephaseProb(), and validateUniqueTargets().
{
     validateDensityMatrQureg(qureg, __func__);
     validateUniqueTargets(qureg, qubit1, qubit2, __func__);
     validateTwoQubitDephaseProb(prob, __func__);
     ensureIndsIncrease(&qubit1, &qubit2);
     densmatr_mixTwoQubitDephasing(qureg, qubit1, qubit2, (4*prob)/3.0);
     qasm_recordComment(qureg,
         "Here, a phase (Z) error occured on either or both of qubits "
         "%d and %d with total probability %g", qubit1, qubit2, prob);
 }
mixTwoQubitDepolarising()
void mixTwoQubitDepolarising (Qureg qureg, int qubit1, int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit homogeneous depolarising noise.
With probability prob, applies to qubit1 and qubit2 any operator of the set . Note this is the set of all two-qubit Pauli gates excluding .
This transforms qureg = into the mixed state
or verbosely
where a = qubit1, b = qubit2. prob cannot exceed 15/16, at which maximal mixing occurs.
Parameters
[in,out] qureg a density matrix
[in] qubit1 qubit upon which to induce depolarising noise
[in] qubit2 qubit upon which to induce depolarising noise
[in] prob the probability of the depolarising error occuring
Exceptions
exitWithError if qureg is not a density matrix, or if either qubit1 or qubit2 is outside [0, qureg.numQubitsRepresented), or if qubit1 = qubit2, or if prob is not in [0, 15/16]
Definition at line 946 of file QuEST.c.
References densmatr_mixTwoQubitDepolarising(), ensureIndsIncrease(), qasm_recordComment(), validateDensityMatrQureg(), validateTwoQubitDepolProb(), and validateUniqueTargets().
{
     validateDensityMatrQureg(qureg, __func__);
     validateUniqueTargets(qureg, qubit1, qubit2, __func__);
     validateTwoQubitDepolProb(prob, __func__);
     ensureIndsIncrease(&qubit1, &qubit2);
     densmatr_mixTwoQubitDepolarising(qureg, qubit1, qubit2, (16*prob)/15.0);
     qasm_recordComment(qureg,
         "Here, a homogeneous depolarising error occured on qubits %d and %d "
         "with total probability %g", qubit1, qubit2, prob);
 }
mixTwoQubitKrausMap()
void mixTwoQubitKrausMap (Qureg qureg, int target1, int target2, ComplexMatrix4 * ops, int numOps)
Apply a general two-qubit Kraus map to a density matrix, as specified by at most sixteen Kraus operators.
A Kraus map is also referred to as a "operator-sum representation" of a quantum channel. This allows one to simulate a general two-qubit noise process.
The Kraus map must be completely positive and trace preserving, which constrains each in ops by
where is the identity matrix.
targetQubit1 is treated as the least significant qubit in each op in ops.
Note that in distributed mode, this routine requires that each node contains at least 16 amplitudes. This means an q-qubit register can be distributed by at most 2^(q-4) numTargs nodes.
Parameters
[in,out] qureg the density matrix to which to apply the map
[in] target1 the least significant target qubit in ops
[in] target2 the most significant target qubit in ops
[in] ops an array of at most 16 Kraus operators
[in] numOps the number of operators in ops which must be >0 and <= 16.
Exceptions
exitWithError if qureg is not a density matrix, or if either target1 or target2 is outside of [0, qureg.numQubitsRepresented), or if target1 = target2, or if numOps is outside [1, 16], or if ops do not create a completely positive, trace preserving map, or if a node cannot fit 16 amplitudes in distributed mode.
Definition at line 979 of file QuEST.c.
References densmatr_mixTwoQubitKrausMap(), qasm_recordComment(), validateDensityMatrQureg(), validateMultiTargets(), and validateTwoQubitKrausMap().
{
     validateDensityMatrQureg(qureg, __func__);
     validateMultiTargets(qureg, (int[]) {target1,target2}, 2, __func__);
     validateTwoQubitKrausMap(qureg, ops, numOps, __func__);
     densmatr_mixTwoQubitKrausMap(qureg, target1, target2, ops, numOps);
     qasm_recordComment(qureg,
         "Here, an undisclosed two-qubit Kraus map was effected on qubits %d and %d", target1, target2);
 }
multiControlledMultiQubitUnitary()
void multiControlledMultiQubitUnitary (Qureg qureg, int * ctrls, const int numCtrls, int * targs, const int numTargs, ComplexMatrixN u)
Apply a general multi-controlled multi-qubit unitary (including a global phase factor).
Any number of control and target qubits can be specified. This effects the many-qubit unitary
on the control and target qubits.
The target qubits in targs are treated as ordered least sigifnicant to most significant in u.
The passed ComplexMatrix must be unitary and be a compatible size with the specified number of target qubits, otherwise an error is thrown.
Note that in distributed mode, this routine requires that each node contains at least 2^numTargs amplitudes. This means an q-qubit register (state vector or density matrix) can be distributed by at most 2^q / 2^numTargs nodes.
Parameters
[in,out] qureg object representing the set of all qubits
[in] ctrls a list of the control qubits
[in] numCtrls the number of control qubits
[in] targs a list of the target qubits, ordered least to most significant
[in] numTargs the number of target qubits
[in] u unitary matrix to apply
Exceptions
exitWithError if any index in ctrls and targs is outside of [0, qureg.numQubitsRepresented), or if ctrls and targs are not unique, or if matrix u is not unitary, or if a node cannot fit the required number of target amplitudes in distributed mode.
Definition at line 341 of file QuEST.c.
References getQubitBitMask(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordComment(), setConjugateMatrixN(), shiftIndices(), statevec_multiControlledMultiQubitUnitary(), validateMultiControlsMultiTargets(), and validateMultiQubitUnitaryMatrix().
{
     validateMultiControlsMultiTargets(qureg, ctrls, numCtrls, targs, numTargs, __func__);
     validateMultiQubitUnitaryMatrix(qureg, u, numTargs, __func__);
     long long int ctrlMask = getQubitBitMask(ctrls, numCtrls);
     statevec_multiControlledMultiQubitUnitary(qureg, ctrlMask, targs, numTargs, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         shiftIndices(targs, numTargs, shift);
         setConjugateMatrixN(u);
         statevec_multiControlledMultiQubitUnitary(qureg, ctrlMask<<shift, targs, numTargs, u);
         shiftIndices(targs, numTargs, -shift);
         setConjugateMatrixN(u);
     }
     qasm_recordComment(qureg, "Here, an undisclosed multi-controlled multi-qubit unitary was applied.");
 }
multiControlledPhaseFlip()
void multiControlledPhaseFlip (Qureg qureg, int * controlQubits, int numControlQubits)
Apply the multiple-qubit controlled phase flip gate, also known as the multiple-qubit controlled pauliZ gate.
For each state, if all control qubits have value one, multiply the amplitude of that state by -1. This applies the many-qubit unitary:
on the control qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubits array of input qubits
[in] numControlQubits number of input qubits
Exceptions
exitWithError if numControlQubits is outside [1, qureg.numQubitsRepresented), or if any qubit in controlQubits is outside [0, qureg.numQubitsRepresented), or if any qubit in qubits is repeated.
Definition at line 570 of file QuEST.c.
References GATE_SIGMA_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordMultiControlledGate(), shiftIndices(), statevec_multiControlledPhaseFlip(), and validateMultiControls().
{
     validateMultiControls(qureg, controlQubits, numControlQubits, __func__);
     statevec_multiControlledPhaseFlip(qureg, controlQubits, numControlQubits);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         shiftIndices(controlQubits, numControlQubits, shift);
         statevec_multiControlledPhaseFlip(qureg, controlQubits, numControlQubits);
         shiftIndices(controlQubits, numControlQubits, -shift);
     }
     qasm_recordMultiControlledGate(qureg, GATE_SIGMA_Z, controlQubits, numControlQubits-1, controlQubits[numControlQubits-1]);
 }
multiControlledPhaseShift()
void multiControlledPhaseShift (Qureg qureg, int * controlQubits, int numControlQubits, qreal angle)
Introduce a phase factor on state of the passed qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubits array of qubits to phase shift
[in] numControlQubits the length of array controlQubits
[in] angle amount by which to shift the phase in radians
Exceptions
exitWithError if numControlQubits is outside [1, qureg.numQubitsRepresented]), or if any qubit index in controlQubits is outside [0, qureg.numQubitsRepresented]), or if any qubit in controlQubits is repeated.
Definition at line 520 of file QuEST.c.
References GATE_PHASE_SHIFT, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordMultiControlledParamGate(), shiftIndices(), statevec_multiControlledPhaseShift(), and validateMultiControls().
{
     validateMultiControls(qureg, controlQubits, numControlQubits, __func__);
     statevec_multiControlledPhaseShift(qureg, controlQubits, numControlQubits, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         shiftIndices(controlQubits, numControlQubits, shift);
         statevec_multiControlledPhaseShift(qureg, controlQubits, numControlQubits, -angle);
         shiftIndices(controlQubits, numControlQubits, -shift);
     }
     qasm_recordMultiControlledParamGate(qureg, GATE_PHASE_SHIFT, controlQubits, numControlQubits-1, controlQubits[numControlQubits-1], angle);
 }
multiControlledTwoQubitUnitary()
void multiControlledTwoQubitUnitary (Qureg qureg, int * controlQubits, const int numControlQubits, const int targetQubit1, const int targetQubit2, ComplexMatrix4 u)
Apply a general multi-controlled two-qubit unitary (including a global phase factor).
Any number of control qubits can be specified, and if all have value 1, the given unitary is applied to the target qubit. This effects the many-qubit unitary
on the control and target qubits.
targetQubit1 is treated as the least significant qubit in u, such that a row in u is dotted with the vector
The passed 4x4 ComplexMatrix must be unitary, otherwise an error is thrown.
Note that in distributed mode, this routine requires that each node contains at least 4 amplitudes. This means an q-qubit register (state vector or density matrix) can be distributed by at most 2^q/4 nodes.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubits the control qubits which all must be in state 1 to effect the given unitary
[in] numControlQubits the number of control qubits
[in] targetQubit1 first target qubit, treated as least significant in u
[in] targetQubit2 second target qubit, treated as most significant in u
[in] u unitary matrix to apply
Exceptions
exitWithError if targetQubit1 or targetQubit2 are outside [0, qureg.numQubitsRepresented), or if targetQubit1 equals targetQubit2, or if any qubit in controlQubits is outside [0, qureg.numQubitsRepresented), or if controlQubits are not unique, or if either targetQubit1 and targetQubit2 are in controlQubits, or if matrix u is not unitary, or if each node cannot fit 4 amplitudes in distributed mode.
Definition at line 293 of file QuEST.c.
References getConjugateMatrix4(), getQubitBitMask(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordComment(), statevec_multiControlledTwoQubitUnitary(), validateMultiControlsMultiTargets(), and validateTwoQubitUnitaryMatrix().
{
     validateMultiControlsMultiTargets(qureg, controlQubits, numControlQubits, (int[]) {targetQubit1, targetQubit2}, 2, __func__);
     validateTwoQubitUnitaryMatrix(qureg, u, __func__);
     long long int ctrlQubitsMask = getQubitBitMask(controlQubits, numControlQubits);
     statevec_multiControlledTwoQubitUnitary(qureg, ctrlQubitsMask, targetQubit1, targetQubit2, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_multiControlledTwoQubitUnitary(qureg, ctrlQubitsMask<<shift, targetQubit1+shift, targetQubit2+shift, getConjugateMatrix4(u));
     }
     qasm_recordComment(qureg, "Here, an undisclosed multi-controlled 2-qubit unitary was applied.");
 }
multiControlledUnitary()
void multiControlledUnitary (Qureg qureg, int * controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
Any number of control qubits can be specified, and if all have value 1, the given unitary is applied to the target qubit. This effects the many-qubit unitary
on the control and target qubits. The given 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubits applies unitary if all qubits in this array equal 1
[in] numControlQubits number of control qubits
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions
exitWithError if numControlQubits is outside [1, qureg.numQubitsRepresented]), or if any qubit index (targetQubit or one in controlQubits) is outside [0, qureg.numQubitsRepresented]), or if any qubit in controlQubits is repeated, or if controlQubits contains targetQubit, or if u is not unitary.
Definition at line 384 of file QuEST.c.
References getConjugateMatrix2(), getQubitBitMask(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordMultiControlledUnitary(), statevec_multiControlledUnitary(), validateMultiControlsTarget(), and validateOneQubitUnitaryMatrix().
{
     validateMultiControlsTarget(qureg, controlQubits, numControlQubits, targetQubit, __func__);
     validateOneQubitUnitaryMatrix(u, __func__);
     long long int ctrlQubitsMask = getQubitBitMask(controlQubits, numControlQubits);
     long long int ctrlFlipMask = 0;
     statevec_multiControlledUnitary(qureg, ctrlQubitsMask, ctrlFlipMask, targetQubit, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_multiControlledUnitary(qureg, ctrlQubitsMask<<shift, ctrlFlipMask<<shift, targetQubit+shift, getConjugateMatrix2(u));
     }
     qasm_recordMultiControlledUnitary(qureg, u, controlQubits, numControlQubits, targetQubit);
 }
multiQubitUnitary()
void multiQubitUnitary (Qureg qureg, int * targs, const int numTargs, ComplexMatrixN u)
Apply a general multi-qubit unitary (including a global phase factor) with any number of target qubits.
The first target qubit in targs is treated as least sigifnicant in u. For example,
multiQubitUnitary(qureg, (int []) {a, b, c}, 3, u);
will invoke multiplication
The passed ComplexMatrix must be unitary and be a compatible size with the specified number of target qubits, otherwise an error is thrown.
Note that in distributed mode, this routine requires that each node contains at least 2^numTargs amplitudes. This means an q-qubit register (state vector or density matrix) can be distributed by at most 2^q / 2^numTargs nodes.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targs a list of the target qubits, ordered least significant to most in u
[in] numTargs the number of target qubits
[in] u unitary matrix to apply
Exceptions
exitWithError if any index in targs is outside of [0, qureg.numQubitsRepresented), or if targs are not unique, or if matrix u is not unitary, or if a node cannot fit the required number of target amplitudes in distributed mode.
Definition at line 307 of file QuEST.c.
References Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordComment(), setConjugateMatrixN(), shiftIndices(), statevec_multiQubitUnitary(), validateMultiQubitUnitaryMatrix(), and validateMultiTargets().
{
     validateMultiTargets(qureg, targs, numTargs, __func__);
     validateMultiQubitUnitaryMatrix(qureg, u, numTargs, __func__);
     statevec_multiQubitUnitary(qureg, targs, numTargs, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         shiftIndices(targs, numTargs, shift);
         setConjugateMatrixN(u);
         statevec_multiQubitUnitary(qureg, targs, numTargs, u);
         shiftIndices(targs, numTargs, -shift);
         setConjugateMatrixN(u);
     }
     qasm_recordComment(qureg, "Here, an undisclosed multi-qubit unitary was applied.");
 }
multiRotatePauli()
void multiRotatePauli (Qureg qureg, int * targetQubits, enum pauliOpType * targetPaulis, int numTargets, qreal angle)
Apply a multi-qubit multi-Pauli rotation on a selected number of qubits.
This is the unitary
where is a Pauli operator (indicated by codes 0, 1, 2, 3 respectively in targetPaulis, or by enums PAULI_I, PAULI_X, PAULI_Y and PAULI_Z) operating upon the qubit targetQubits[j], and is the passed angle. The operators specified in targetPaulis act on the corresponding qubit in targetQubits. For example:
multiRotatePauli(qureg, (int[]) {4,5,8,9}, (int[]) {0,1,2,3}, 4, .1)
effects on qureg, where unspecified qubits (along with those specified with Pauli code 0) are assumed to receive the identity operator. Note that specifying the identity Pauli (code=0) on a qubit is superfluous but allowed for convenience.
This function effects this unitary by first rotating the qubits which are nominated to receive X or Y Paulis into alternate basis, performing multiRotateZ on all target qubits receiving X, Y or Z Paulis, then restoring the original basis. In the worst case, this means that 1+2*numTargets primitive unitaries are performed on the statevector, and double this on density matrices.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubits a list of the indices of the target qubits
[in] targetPaulis a list of the Pauli codes (0=PAULI_I, 1=PAULI_X, 2=PAULI_Y, 3=PAULI_Z) to apply to the corresponding qubits in targetQubits
[in] numTargets number of target qubits, i.e. the length of targetQubits and targetPaulis
[in] angle the angle by which the multi-qubit state is rotated
Exceptions
exitWithError if numQubits is outside [1, qureg.numQubitsRepresented]), or if any qubit in qubits is outside [0, qureg.numQubitsRepresented)) or if any qubit in qubits is repeated.
Definition at line 651 of file QuEST.c.
References Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordComment(), shiftIndices(), statevec_multiRotatePauli(), validateMultiTargets(), and validatePauliCodes().
{
     validateMultiTargets(qureg, targetQubits, numTargets, __func__);
     validatePauliCodes(targetPaulis, numTargets, __func__);
     int conj=0;
     statevec_multiRotatePauli(qureg, targetQubits, targetPaulis, numTargets, angle, conj);
     if (qureg.isDensityMatrix) {
         conj = 1;
         int shift = qureg.numQubitsRepresented;
         shiftIndices(targetQubits, numTargets, shift);
         statevec_multiRotatePauli(qureg, targetQubits, targetPaulis, numTargets, angle, conj);
         shiftIndices(targetQubits, numTargets, -shift);
     }
     // @TODO: create actual QASM
     qasm_recordComment(qureg,
         "Here a %d-qubit multiRotatePauli of angle %g was performed (QASM not yet implemented)",
         numTargets, angle);
 }
multiRotateZ()
void multiRotateZ (Qureg qureg, int * qubits, int numQubits, qreal angle)
Apply a multi-qubit Z rotation on a selected number of qubits.
This is the unitary
where the Pauli Z gates operate upon the passed list qubits, and cause rotations of angle. All qubits not appearing in qubits are assumed to receive the identity operator. This has the effect of premultiplying every amplitude with where the sign is determined by the parity of the target qubits for that amplitude.
Parameters
[in,out] qureg object representing the set of all qubits
[in] qubits a list of the indices of the target qubits
[in] numQubits number of target qubits
[in] angle the angle by which the multi-qubit state is rotated around the Z axis
Exceptions
exitWithError if numQubits is outside [1, qureg.numQubitsRepresented]), or if any qubit in qubits is outside [0, qureg.numQubitsRepresented]) or if any qubit in qubits is repeated.
Definition at line 635 of file QuEST.c.
References getQubitBitMask(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordComment(), statevec_multiRotateZ(), and validateMultiTargets().
{
     validateMultiTargets(qureg, qubits, numQubits, __func__);
     long long int mask = getQubitBitMask(qubits, numQubits);
     statevec_multiRotateZ(qureg, mask, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_multiRotateZ(qureg, mask << shift, -angle);
     }
     // @TODO: create actual QASM
     qasm_recordComment(qureg,
         "Here a %d-qubit multiRotateZ of angle %g was performed (QASM not yet implemented)",
         numQubits, angle);
 }
multiStateControlledUnitary()
void multiStateControlledUnitary (Qureg qureg, int * controlQubits, int * controlState, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control, conditioned on a specific bit sequence, single-target unitary, which can include a global phase factor.
Any number of control qubits can be specified, along with which of their states (0 or 1) to condition upon; when the specified controls are in the specified state, the given unitary is applied to the target qubit. This is equivalent to NOTing the control bits which are conditioned on 0, calling multiControlledUnitary then NOTing the same control bits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubits the indices of the control qubits
[in] controlState the bit values (0 or 1) of each control qubit, upon which to condition
[in] numControlQubits number of control qubits
[in] targetQubit qubit to operate the unitary upon
[in] u single-qubit unitary matrix to apply
Exceptions
exitWithError if numControlQubits is outside [1, qureg.numQubitsRepresented]), or if any qubit index (targetQubit or one in controlQubits) is outside [0, qureg.numQubitsRepresented]), or if any qubit in controlQubits is repeated., or if controlQubits contains targetQubit, or if any element of controlState is not a bit (0 or 1), or if u is not unitary.
Definition at line 399 of file QuEST.c.
References getConjugateMatrix2(), getControlFlipMask(), getQubitBitMask(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordMultiStateControlledUnitary(), statevec_multiControlledUnitary(), validateControlState(), validateMultiControlsTarget(), and validateOneQubitUnitaryMatrix().
{
     validateMultiControlsTarget(qureg, controlQubits, numControlQubits, targetQubit, __func__);
     validateOneQubitUnitaryMatrix(u, __func__);
     validateControlState(controlState, numControlQubits, __func__);
     long long int ctrlQubitsMask = getQubitBitMask(controlQubits, numControlQubits);
     long long int ctrlFlipMask = getControlFlipMask(controlQubits, controlState, numControlQubits);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_multiControlledUnitary(qureg, ctrlQubitsMask<<shift, ctrlFlipMask<<shift, targetQubit+shift, getConjugateMatrix2(u));
     }
     qasm_recordMultiStateControlledUnitary(qureg, u, controlQubits, controlState, numControlQubits, targetQubit);
 }
pauliX()
void pauliX (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-X (also known as the X, sigma-X, NOT or bit-flip) gate.
This is a rotation of around the x-axis on the Bloch sphere. I.e.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 442 of file QuEST.c.
References GATE_SIGMA_X, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_pauliX(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_pauliX(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_pauliX(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_SIGMA_X, targetQubit);
 }
pauliY()
void pauliY (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-Y (also known as the Y or sigma-Y) gate.
This is a rotation of around the Y-axis on the Bloch sphere. I.e.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 453 of file QuEST.c.
References GATE_SIGMA_Y, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_pauliY(), statevec_pauliYConj(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_pauliY(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_pauliYConj(qureg, targetQubit + qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_SIGMA_Y, targetQubit);
 }
pauliZ()
void pauliZ (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-Z (also known as the Z, sigma-Z or phase-flip) gate.
This is a rotation of around the Z-axis (a phase shift) on the Bloch sphere. I.e.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 464 of file QuEST.c.
References GATE_SIGMA_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_pauliZ(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_pauliZ(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_pauliZ(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_SIGMA_Z, targetQubit);
 }
phaseShift()
void phaseShift (Qureg qureg, const int targetQubit, qreal angle)
Shift the phase between and of a single qubit by a given angle.
This is equivalent to a rotation Z-axis of the Bloch-sphere up to a global phase factor. For angle , applies
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to undergo a phase shift
[in] angle amount by which to shift the phase in radians
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 497 of file QuEST.c.
References GATE_PHASE_SHIFT, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordParamGate(), statevec_phaseShift(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_phaseShift(qureg, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         statevec_phaseShift(qureg, targetQubit+qureg.numQubitsRepresented, -angle);
     }
     qasm_recordParamGate(qureg, GATE_PHASE_SHIFT, targetQubit, angle);
 }
printRecordedQASM()
void printRecordedQASM (Qureg qureg)
Print recorded QASM to stdout.
Definition at line 108 of file QuEST.c.
References qasm_printRecorded().
{
     qasm_printRecorded(qureg);
 }
reportStateToScreen()
void reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
For debugging purposes. Each rank should print output serially. Only print output for systems <= 5 qubits
Definition at line 1068 of file QuEST.c.
References statevec_reportStateToScreen().
{
     statevec_reportStateToScreen(qureg, env, reportRank);
 }
rotateAroundAxis()
void rotateAroundAxis (Qureg qureg, const int rotQubit, qreal angle, Vector axis)
Rotate a single qubit by a given angle around a given vector on the Bloch-sphere.
The vector must not be zero (else an error is thrown), but needn't be unit magnitude.
For angle and axis vector , applies where is the vector of Pauli matrices.
Parameters
[in,out] qureg object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
[in] axis vector around which to rotate (can be non-unit; will be normalised)
Exceptions
exitWithError if rotQubit is outside [0, qureg.numQubitsRepresented), or if axis is the zero vector
Definition at line 584 of file QuEST.c.
References Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordAxisRotation(), statevec_rotateAroundAxis(), statevec_rotateAroundAxisConj(), validateTarget(), and validateVector().
{
     validateTarget(qureg, rotQubit, __func__);
     validateVector(axis, __func__);
     statevec_rotateAroundAxis(qureg, rotQubit, angle, axis);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_rotateAroundAxisConj(qureg, rotQubit+shift, angle, axis);
     }
     qasm_recordAxisRotation(qureg, angle, axis, rotQubit);
 }
rotateX()
void rotateX (Qureg qureg, const int rotQubit, qreal angle)
Rotate a single qubit by a given angle around the X-axis of the Bloch-sphere.
For angle , applies
Parameters
[in,out] qureg object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions
exitWithError if rotQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 198 of file QuEST.c.
References GATE_ROTATE_X, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordParamGate(), statevec_rotateX(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_rotateX(qureg, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         statevec_rotateX(qureg, targetQubit+qureg.numQubitsRepresented, -angle);
     }
     qasm_recordParamGate(qureg, GATE_ROTATE_X, targetQubit, angle);
 }
rotateY()
void rotateY (Qureg qureg, const int rotQubit, qreal angle)
Rotate a single qubit by a given angle around the Y-axis of the Bloch-sphere.
For angle , applies
Parameters
[in,out] qureg object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions
exitWithError if rotQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 209 of file QuEST.c.
References GATE_ROTATE_Y, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordParamGate(), statevec_rotateY(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_rotateY(qureg, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         statevec_rotateY(qureg, targetQubit+qureg.numQubitsRepresented, angle);
     }
     qasm_recordParamGate(qureg, GATE_ROTATE_Y, targetQubit, angle);
 }
rotateZ()
void rotateZ (Qureg qureg, const int rotQubit, qreal angle)
Rotate a single qubit by a given angle around the Z-axis of the Bloch-sphere (also known as a phase shift gate).
For angle , applies
Parameters
[in,out] qureg object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions
exitWithError if rotQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 220 of file QuEST.c.
References GATE_ROTATE_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordParamGate(), statevec_rotateZ(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_rotateZ(qureg, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         statevec_rotateZ(qureg, targetQubit+qureg.numQubitsRepresented, -angle);
     }
     qasm_recordParamGate(qureg, GATE_ROTATE_Z, targetQubit, angle);
 }
setAmps()
void setAmps (Qureg qureg, long long int startInd, qreal * reals, qreal * imags, long long int numAmps)
Edit qureg to adopt the subset of amplitudes passed in reals and imags.
Only amplitudes with indices in [startInd, startInd + numAmps] will be changed, which means the new state may not be L2 normalised. This allows the user to initialise a custom state by setting batches of amplitudes.
Parameters
[in,out] qureg the statevector to modify
[in] startInd the index of the first amplitude in qureg's statevector to modify
[in] reals array of the real components of the new amplitudes
[in] imags array of the imaginary components of the new amplitudes
[in] numAmps the length of each of the reals and imags arrays.
Exceptions
exitWithError if qureg is not a statevector (i.e. is a density matrix)
Definition at line 790 of file QuEST.c.
References qasm_recordComment(), statevec_setAmps(), validateNumAmps(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateNumAmps(qureg, startInd, numAmps, __func__);
     statevec_setAmps(qureg, startInd, reals, imags, numAmps);
     qasm_recordComment(qureg, "Here, some amplitudes in the statevector were manually edited.");
 }
setDensityAmps()
void setDensityAmps (Qureg qureg, qreal * reals, qreal * imags)
Set elements in the underlying state vector represenation of a density matrix.
Not exposed in the public API as this requires an understanding of how the state vector is used to represent a density matrix. Currently can only be used to set all amps.
Definition at line 799 of file QuEST.c.
References Qureg::numAmpsTotal, qasm_recordComment(), and statevec_setAmps().
{
     long long int numAmps = qureg.numAmpsTotal;
     statevec_setAmps(qureg, 0, reals, imags, numAmps);
     qasm_recordComment(qureg, "Here, some amplitudes in the density matrix were manually edited.");
 }
setWeightedQureg()
void setWeightedQureg (Complex fac1, Qureg qureg1, Complex fac2, Qureg qureg2, Complex facOut, Qureg out)
Modifies qureg out to the result of (facOut out + fac1 qureg1 + fac2 qureg2), imposing no constraints on normalisation.
Works for both statevectors and density matrices. Note that afterward, out may not longer be normalised and ergo no longer a valid statevector or density matrix. Users must therefore be careful passing out to other QuEST functions which assume normalisation in order to function correctly.
qureg1, qureg2 and out must be all state-vectors, or all density matrices, of equal dimensions. out can be one (or both) of qureg1 and qureg2.
Parameters
[in] fac1 the complex number by which to scale qureg1 in the output state
[in] qureg1 the first qureg to add to out, which is itself unmodified
[in] fac2 the complex number by which to scale qureg2 in the output state
[in] qureg2 the second qureg to add to out, which is itself unmodified
[in] facOut the complex factor by which to multiply the current elements of out. out is completely overwritten if facOut is set to (Complex) {.real=0,.imag=0}
[in,out] out the qureg to be modified, to be scaled by facOut then have fac1 qureg1 and fac2 qureg2 added to it.
Exceptions
exitWithError if qureg1, qureg2 and aren't all state-vectors or all density matrices, or if the dimensions of qureg1, qureg2 and aren't equal
Definition at line 806 of file QuEST.c.
References qasm_recordComment(), statevec_setWeightedQureg(), validateMatchingQuregDims(), and validateMatchingQuregTypes().
Referenced by statevec_applyPauliSum().
{
     validateMatchingQuregTypes(qureg1, qureg2, __func__);
     validateMatchingQuregTypes(qureg1, out, __func__);
     validateMatchingQuregDims(qureg1, qureg2,  __func__);
     validateMatchingQuregDims(qureg1, out, __func__);
     statevec_setWeightedQureg(fac1, qureg1, fac2, qureg2, facOut, out);
     qasm_recordComment(out, "Here, the register was modified to an undisclosed and possibly unphysical state (setWeightedQureg).");
 }
sGate()
void sGate (Qureg qureg, const int targetQubit)
Apply the single-qubit S gate.
This is a rotation of around the Z-axis on the Bloch sphere, or the unitary:
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate upon
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented)
Definition at line 475 of file QuEST.c.
References GATE_S, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_sGate(), statevec_sGateConj(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_sGate(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_sGateConj(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_S, targetQubit);
 }
sqrtSwapGate()
void sqrtSwapGate (Qureg qureg, int qb1, int qb2)
Performs a sqrt SWAP gate between qubit1 and qubit2.
This effects
on the designated qubits, though is performed internally by three CNOT gates.
Parameters
[in,out] qureg object representing the set of all qubits
[in] qubit1 qubit to sqrt swap
[in] qubit2 other qubit to sqrt swap
Exceptions
exitWithError if either qubit1 or qubit2 are outside [0, qureg.numQubitsRepresented), or are equal.
Definition at line 622 of file QuEST.c.
References GATE_SQRT_SWAP, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledGate(), statevec_sqrtSwapGate(), statevec_sqrtSwapGateConj(), validateControlTarget(), and validateMultiQubitMatrixFitsInNode().
{
     validateControlTarget(qureg, qb1, qb2, __func__);
     validateMultiQubitMatrixFitsInNode(qureg, 2, __func__); // uses 2qb unitary in QuEST_common
     statevec_sqrtSwapGate(qureg, qb1, qb2);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_sqrtSwapGateConj(qureg, qb1+shift, qb2+shift);
     }
     qasm_recordControlledGate(qureg, GATE_SQRT_SWAP, qb1, qb2);
 }
startRecordingQASM()
void startRecordingQASM (Qureg qureg)
Enable QASM recording.
Gates applied to qureg will here-after be added to growing QASM instructions, progressively consuming more memory until stopped
Definition at line 96 of file QuEST.c.
References qasm_startRecording().
{
     qasm_startRecording(qureg);
 }
stopRecordingQASM()
void stopRecordingQASM (Qureg qureg)
Disable QASM recording.
The recorded QASM will be maintained in qureg and continue to be added to if startRecordingQASM is recalled.
Definition at line 100 of file QuEST.c.
References qasm_stopRecording().
{
     qasm_stopRecording(qureg);
 }
swapGate()
void swapGate (Qureg qureg, int qubit1, int qubit2)
Performs a SWAP gate between qubit1 and qubit2.
This effects
on the designated qubits, though is performed internally by three CNOT gates.
Parameters
[in,out] qureg object representing the set of all qubits
[in] qubit1 qubit to swap
[in] qubit2 other qubit to swap
Exceptions
exitWithError if either qubit1 or qubit2 are outside [0, qureg.numQubitsRepresented), or are equal.
Definition at line 610 of file QuEST.c.
References GATE_SWAP, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledGate(), statevec_swapQubitAmps(), and validateControlTarget().
{
     validateControlTarget(qureg, qb1, qb2, __func__);
     statevec_swapQubitAmps(qureg, qb1, qb2);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_swapQubitAmps(qureg, qb1+shift, qb2+shift);
     }
     qasm_recordControlledGate(qureg, GATE_SWAP, qb1, qb2);
 }
tGate()
void tGate (Qureg qureg, const int targetQubit)
Apply the single-qubit T gate.
This is a rotation of around the Z-axis on the Bloch sphere, or the unitary:
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate upon
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented)
Definition at line 486 of file QuEST.c.
References GATE_T, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_tGate(), statevec_tGateConj(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_tGate(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_tGateConj(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_T, targetQubit);
 }
twoQubitUnitary()
void twoQubitUnitary (Qureg qureg, const int targetQubit1, const int targetQubit2, ComplexMatrix4 u)
Apply a general two-qubit unitary (including a global phase factor).
targetQubit1 is treated as the least significant qubit in u, such that a row in u is dotted with the vector
For example,
twoQubitUnitary(qureg, a, b, u);
will invoke multiplication
The passed 4x4 ComplexMatrix must be unitary, otherwise an error is thrown.
Note that in distributed mode, this routine requires that each node contains at least 4 amplitudes. This means an q-qubit register (state vector or density matrix) can be distributed by at most 2^q/4 nodes.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit1 first qubit to operate on, treated as least significant in u
[in] targetQubit2 second qubit to operate on, treated as most significant in u
[in] u unitary matrix to apply
Exceptions
exitWithError if targetQubit1 or targetQubit2 are outside [0, qureg.numQubitsRepresented), or if targetQubit1 equals targetQubit2, or matrix u is not unitary, or if each node cannot fit 4 amplitudes in distributed mode.
Definition at line 267 of file QuEST.c.
References getConjugateMatrix4(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordComment(), statevec_twoQubitUnitary(), validateMultiTargets(), and validateTwoQubitUnitaryMatrix().
{
     validateMultiTargets(qureg, (int []) {targetQubit1, targetQubit2}, 2, __func__);
     validateTwoQubitUnitaryMatrix(qureg, u, __func__);
     statevec_twoQubitUnitary(qureg, targetQubit1, targetQubit2, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_twoQubitUnitary(qureg, targetQubit1+shift, targetQubit2+shift, getConjugateMatrix4(u));
     }
     qasm_recordComment(qureg, "Here, an undisclosed 2-qubit unitary was applied.");
 }
unitary()
void unitary (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
The passed 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] u unitary matrix to apply
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented), or matrix u is not unitary.
Definition at line 359 of file QuEST.c.
References getConjugateMatrix2(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordUnitary(), statevec_unitary(), validateOneQubitUnitaryMatrix(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     validateOneQubitUnitaryMatrix(u, __func__);
     statevec_unitary(qureg, targetQubit, u);
     if (qureg.isDensityMatrix) {
         statevec_unitary(qureg, targetQubit+qureg.numQubitsRepresented, getConjugateMatrix2(u));
     }
     qasm_recordUnitary(qureg, u, targetQubit);
 }
writeRecordedQASMToFile()
void writeRecordedQASMToFile (Qureg qureg, char * filename)
Writes recorded QASM to a file, throwing an error if inaccessible.
Definition at line 112 of file QuEST.c.
References qasm_writeRecordedToFile(), and validateFileOpened().
{
     int success = qasm_writeRecordedToFile(qureg, filename);
     validateFileOpened(success, __func__);
 }