Quantum Exact Simulation Toolkit: QuEST_cpu_local.c File Reference
QuEST_cpu_local.c File Reference
An implementation of the pure backend in ../QuEST_ops_pure.h for a local (non-MPI, non-GPU) environment.
#include "QuEST.h"
#include "QuEST_internal.h"
#include "QuEST_precision.h"
#include "mt19937ar.h"
#include "QuEST_cpu_internal.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <time.h>
#include <sys/types.h>
Functions
QuESTEnv createQuESTEnv (void)
Create the QuEST execution environment.
qreal densmatr_calcFidelity (Qureg qureg, Qureg pureState)
qreal densmatr_calcHilbertSchmidtDistance (Qureg a, Qureg b)
qreal densmatr_calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
qreal densmatr_calcPurity (Qureg qureg)
qreal densmatr_calcTotalProb (Qureg qureg)
void densmatr_initPureState (Qureg qureg, Qureg pureState)
void densmatr_mixDamping (Qureg qureg, const int targetQubit, qreal damping)
void densmatr_mixDepolarising (Qureg qureg, const int targetQubit, qreal depolLevel)
void densmatr_mixTwoQubitDepolarising (Qureg qureg, int qubit1, int qubit2, qreal depolLevel)
void destroyQuESTEnv (QuESTEnv env)
Destroy the QuEST environment.
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
void seedQuESTDefault (void)
Seed the Mersenne Twister used for random number generation in the QuEST environment with an example defualt seed.
Complex statevec_calcInnerProduct (Qureg bra, Qureg ket)
qreal statevec_calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
qreal statevec_calcTotalProb (Qureg qureg)
void statevec_collapseToKnownProbOutcome (Qureg qureg, const int measureQubit, int outcome, qreal stateProb)
void statevec_compactUnitary (Qureg qureg, const int targetQubit, Complex alpha, Complex beta)
void statevec_controlledCompactUnitary (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
void statevec_controlledNot (Qureg qureg, const int controlQubit, const int targetQubit)
void statevec_controlledPauliY (Qureg qureg, const int controlQubit, const int targetQubit)
void statevec_controlledPauliYConj (Qureg qureg, const int controlQubit, const int targetQubit)
void statevec_controlledUnitary (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
qreal statevec_getImagAmp (Qureg qureg, long long int index)
qreal statevec_getRealAmp (Qureg qureg, long long int index)
void statevec_hadamard (Qureg qureg, const int targetQubit)
void statevec_multiControlledMultiQubitUnitary (Qureg qureg, long long int ctrlMask, int *targs, const int numTargs, ComplexMatrixN u)
This calls swapQubitAmps only when it would involve a distributed communication; if the qubit chunks already fit in the node, it operates the unitary direct.
void statevec_multiControlledTwoQubitUnitary (Qureg qureg, long long int ctrlMask, const int q1, const int q2, ComplexMatrix4 u)
This calls swapQubitAmps only when it would involve a distributed communication; if the qubit chunks already fit in the node, it operates the unitary direct.
void statevec_multiControlledUnitary (Qureg qureg, long long int ctrlQubitsMask, long long int ctrlFlipMask, const int targetQubit, ComplexMatrix2 u)
void statevec_pauliX (Qureg qureg, const int targetQubit)
void statevec_pauliY (Qureg qureg, const int targetQubit)
void statevec_pauliYConj (Qureg qureg, const int targetQubit)
void statevec_swapQubitAmps (Qureg qureg, int qb1, int qb2)
void statevec_unitary (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
Detailed Description
An implementation of the pure backend in ../QuEST_ops_pure.h for a local (non-MPI, non-GPU) environment.
Mostly pure-state wrappers for the local/distributed functions implemented in QuEST_cpu
Definition in file QuEST_cpu_local.c.
Function Documentation
createQuESTEnv()
QuESTEnv createQuESTEnv (void)
Create the QuEST execution environment.
This should be called only once, and the environment should be freed with destroyQuESTEnv at the end of the user's code. If something needs to be done to set up the execution environment, such as initializing MPI when running in distributed mode, it is handled here.
Returns
object representing the execution environment. A single instance is used for each program
Definition at line 160 of file QuEST_cpu_local.c.
References QuESTEnv::numRanks, QuESTEnv::rank, and seedQuESTDefault().
{
     // init MPI environment
     QuESTEnv env;
     env.rank=0;
     env.numRanks=1;
     seedQuESTDefault();
     return env;
 }
densmatr_calcFidelity()
qreal densmatr_calcFidelity (Qureg qureg, Qureg pureState)
Definition at line 64 of file QuEST_cpu_local.c.
References densmatr_calcFidelityLocal(), Qureg::pairStateVec, qreal, and Qureg::stateVec.
{
     // save pointers to qureg's pair state
     qreal* quregPairRePtr = qureg.pairStateVec.real;
     qreal* quregPairImPtr = qureg.pairStateVec.imag;
     // populate qureg pair state with pure state (by repointing)
     qureg.pairStateVec.real = pureState.stateVec.real;
     qureg.pairStateVec.imag = pureState.stateVec.imag;
     // calculate fidelity using pairState
     qreal fid = densmatr_calcFidelityLocal(qureg, pureState);
     // restore pointers
     qureg.pairStateVec.real = quregPairRePtr;
     qureg.pairStateVec.imag = quregPairImPtr;
     return fid;
 }
densmatr_calcHilbertSchmidtDistance()
qreal densmatr_calcHilbertSchmidtDistance (Qureg a, Qureg b)
Definition at line 57 of file QuEST_cpu_local.c.
References densmatr_calcHilbertSchmidtDistanceSquaredLocal(), and qreal.
{
     qreal distSquared = densmatr_calcHilbertSchmidtDistanceSquaredLocal(a, b);
     qreal dist = sqrt(distSquared);
     return dist;
 }
densmatr_calcProbOfOutcome()
qreal densmatr_calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
Definition at line 277 of file QuEST_cpu_local.c.
References densmatr_findProbabilityOfZeroLocal(), and qreal.
{
     qreal outcomeProb = densmatr_findProbabilityOfZeroLocal(qureg, measureQubit);
     if (outcome == 1)
         outcomeProb = 1.0 - outcomeProb;
     return outcomeProb;
 }
densmatr_calcPurity()
qreal densmatr_calcPurity (Qureg qureg)
Definition at line 53 of file QuEST_cpu_local.c.
References densmatr_calcPurityLocal().
{
     return densmatr_calcPurityLocal(qureg);
 }
densmatr_calcTotalProb()
qreal densmatr_calcTotalProb (Qureg qureg)
Definition at line 106 of file QuEST_cpu_local.c.
References Qureg::numQubitsRepresented, qreal, and Qureg::stateVec.
{
     // computes the trace using Kahan summation
     qreal pTotal=0;
     qreal y, t, c;
     c = 0;
     long long int numCols = 1LL << qureg.numQubitsRepresented;
     long long diagIndex;
     for (int col=0; col< numCols; col++) {
         diagIndex = col*(numCols + 1);
         y = qureg.stateVec.real[diagIndex] - c;
         t = pTotal + y;
         c = ( t - pTotal ) - y; // brackets are important
         pTotal = t;
     }
     // @TODO should maybe do a cheap test that imaginary components are ~0
     return pTotal;
 }
densmatr_initPureState()
void densmatr_initPureState (Qureg qureg, Qureg pureState)
Definition at line 84 of file QuEST_cpu_local.c.
References densmatr_initPureStateLocal(), Qureg::pairStateVec, qreal, and Qureg::stateVec.
{
     // save pointers to qureg's pair state
     qreal* quregPairRePtr = qureg.pairStateVec.real;
     qreal* quregPairImPtr = qureg.pairStateVec.imag;
     // populate qureg pair state with pure state (by repointing)
     qureg.pairStateVec.real = pureState.stateVec.real;
     qureg.pairStateVec.imag = pureState.stateVec.imag;
     // populate density matrix via it's pairState
     densmatr_initPureStateLocal(qureg, pureState);
     // restore pointers
     qureg.pairStateVec.real = quregPairRePtr;
     qureg.pairStateVec.imag = quregPairImPtr;
 }
densmatr_mixDamping()
void densmatr_mixDamping (Qureg qureg, const int targetQubit, qreal damping)
Definition at line 33 of file QuEST_cpu_local.c.
References densmatr_mixDampingLocal().
{
     if (damping == 0)
         return;
     densmatr_mixDampingLocal(qureg, targetQubit, damping);
 }
densmatr_mixDepolarising()
void densmatr_mixDepolarising (Qureg qureg, const int targetQubit, qreal depolLevel)
Definition at line 26 of file QuEST_cpu_local.c.
References densmatr_mixDepolarisingLocal().
{
     if (depolLevel == 0)
         return;
     densmatr_mixDepolarisingLocal(qureg, targetQubit, depolLevel);
 }
densmatr_mixTwoQubitDepolarising()
void densmatr_mixTwoQubitDepolarising (Qureg qureg, int qubit1, int qubit2, qreal depolLevel)
Definition at line 40 of file QuEST_cpu_local.c.
References densmatr_mixTwoQubitDephasing(), densmatr_mixTwoQubitDepolarisingLocal(), and qreal.
{
     if (depolLevel == 0)
         return;
     qreal eta = 2/depolLevel;
     qreal delta = eta - 1 - sqrt( (eta-1)*(eta-1) - 1 );
     qreal gamma = 1+delta;
     // TODO -- test delta too small
     gamma = 1/(gamma*gamma*gamma);
     densmatr_mixTwoQubitDephasing(qureg, qubit1, qubit2, depolLevel);
     densmatr_mixTwoQubitDepolarisingLocal(qureg, qubit1, qubit2, delta, gamma);
 }
destroyQuESTEnv()
void destroyQuESTEnv (QuESTEnv env)
Destroy the QuEST environment.
If something needs to be done to clean up the execution environment, such as finalizing MPI when running in distributed mode, it is handled here
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 180 of file QuEST_cpu_local.c.
{
     // MPI finalize goes here in MPI version. Call this function anyway for consistency
 }
reportQuESTEnv()
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 184 of file QuEST_cpu_local.c.
References QuESTEnv::numRanks, and qreal.
{
     printf("EXECUTION ENVIRONMENT:\n");
     printf("Running locally on one node\n");
     printf("Number of ranks is %d\n", env.numRanks);
 # ifdef _OPENMP
     printf("OpenMP enabled\n");
     printf("Number of threads available is %d\n", omp_get_max_threads());
 # else
     printf("OpenMP disabled\n");
 # endif
     printf("Precision: size of qreal is %ld bytes\n", sizeof(qreal));
 }
seedQuESTDefault()
void seedQuESTDefault (void)
Seed the Mersenne Twister used for random number generation in the QuEST environment with an example defualt seed.
This default seeding function uses the mt19937 init_by_array function with two keys – time and pid. Subsequent calls to mt19937 genrand functions will use this seeding. For a multi process code, the same seed is given to all process, therefore this seeding is only appropriate to use for functions such as measure where all processes require the same random value.
For more information about the MT, see http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/MT2002/emt19937ar.html
Definition at line 290 of file QuEST_cpu_local.c.
References getQuESTDefaultSeedKey(), and init_by_array().
Referenced by createQuESTEnv().
{
     // init MT random number generator with three keys -- time and pid
     // for the MPI version, it is ok that all procs will get the same seed as random numbers will only be
     // used by the master process
     unsigned long int key[2];
     getQuESTDefaultSeedKey(key);
     init_by_array(key, 2);
 }
statevec_calcInnerProduct()
Complex statevec_calcInnerProduct (Qureg bra, Qureg ket)
Definition at line 102 of file QuEST_cpu_local.c.
References statevec_calcInnerProductLocal().
{
     return statevec_calcInnerProductLocal(bra, ket);
 }
statevec_calcProbOfOutcome()
qreal statevec_calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
Definition at line 269 of file QuEST_cpu_local.c.
References qreal, and statevec_findProbabilityOfZeroLocal().
 {
     qreal stateProb=0;
     stateProb = statevec_findProbabilityOfZeroLocal(qureg, measureQubit);
     if (outcome==1) stateProb = 1.0 - stateProb;
     return stateProb;
 }
statevec_calcTotalProb()
qreal statevec_calcTotalProb (Qureg qureg)
Definition at line 129 of file QuEST_cpu_local.c.
References Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
{
     // implemented using Kahan summation for greater accuracy at a slight floating
     // point operation overhead. For more details see https://en.wikipedia.org/wiki/Kahan_summation_algorithm
     qreal pTotal=0;
     qreal y, t, c;
     long long int index;
     long long int numAmpsPerRank = qureg.numAmpsPerChunk;
     c = 0.0;
     for (index=0; index<numAmpsPerRank; index++){
         // Perform pTotal+=qureg.stateVec.real[index]*qureg.stateVec.real[index]; by Kahan
         y = qureg.stateVec.real[index]*qureg.stateVec.real[index] - c;
         t = pTotal + y;
         // Don't change the bracketing on the following line
         c = ( t - pTotal ) - y;
         pTotal = t;
         // Perform pTotal+=qureg.stateVec.imag[index]*qureg.stateVec.imag[index]; by Kahan
         y = qureg.stateVec.imag[index]*qureg.stateVec.imag[index] - c;
         t = pTotal + y;
         // Don't change the bracketing on the following line
         c = ( t - pTotal ) - y;
         pTotal = t;
     }
     return pTotal;
 }
statevec_collapseToKnownProbOutcome()
void statevec_collapseToKnownProbOutcome (Qureg qureg, const int measureQubit, int outcome, qreal stateProb)
Definition at line 285 of file QuEST_cpu_local.c.
References statevec_collapseToKnownProbOutcomeLocal().
 {
     statevec_collapseToKnownProbOutcomeLocal(qureg, measureQubit, outcome, stateProb);
 }
statevec_compactUnitary()
void statevec_compactUnitary (Qureg qureg, const int targetQubit, Complex alpha, Complex beta)
Definition at line 205 of file QuEST_cpu_local.c.
References statevec_compactUnitaryLocal().
 {
     statevec_compactUnitaryLocal(qureg, targetQubit, alpha, beta);
 }
statevec_controlledCompactUnitary()
void statevec_controlledCompactUnitary (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Definition at line 215 of file QuEST_cpu_local.c.
References statevec_controlledCompactUnitaryLocal().
 {
     statevec_controlledCompactUnitaryLocal(qureg, controlQubit, targetQubit, alpha, beta);
 }
statevec_controlledNot()
void statevec_controlledNot (Qureg qureg, const int controlQubit, const int targetQubit)
Definition at line 264 of file QuEST_cpu_local.c.
References statevec_controlledNotLocal().
 {
     statevec_controlledNotLocal(qureg, controlQubit, targetQubit);
 }
statevec_controlledPauliY()
void statevec_controlledPauliY (Qureg qureg, const int controlQubit, const int targetQubit)
Definition at line 247 of file QuEST_cpu_local.c.
References statevec_controlledPauliYLocal().
 {
     int conjFac = 1;
     statevec_controlledPauliYLocal(qureg, controlQubit, targetQubit, conjFac);
 }
statevec_controlledPauliYConj()
void statevec_controlledPauliYConj (Qureg qureg, const int controlQubit, const int targetQubit)
Definition at line 253 of file QuEST_cpu_local.c.
References statevec_controlledPauliYLocal().
 {
     int conjFac = -1;
     statevec_controlledPauliYLocal(qureg, controlQubit, targetQubit, conjFac);
 }
statevec_controlledUnitary()
void statevec_controlledUnitary (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Definition at line 220 of file QuEST_cpu_local.c.
References statevec_controlledUnitaryLocal().
 {
     statevec_controlledUnitaryLocal(qureg, controlQubit, targetQubit, u);
 }
statevec_getImagAmp()
qreal statevec_getImagAmp (Qureg qureg, long long int index)
Definition at line 201 of file QuEST_cpu_local.c.
References Qureg::stateVec.
{
     return qureg.stateVec.imag[index];
 }
statevec_getRealAmp()
qreal statevec_getRealAmp (Qureg qureg, long long int index)
Definition at line 197 of file QuEST_cpu_local.c.
References Qureg::stateVec.
{
     return qureg.stateVec.real[index];
 }
statevec_hadamard()
void statevec_hadamard (Qureg qureg, const int targetQubit)
Definition at line 259 of file QuEST_cpu_local.c.
References statevec_hadamardLocal().
 {
     statevec_hadamardLocal(qureg, targetQubit);
 }
statevec_multiControlledMultiQubitUnitary()
void statevec_multiControlledMultiQubitUnitary (Qureg qureg, long long int ctrlMask, int * targs, const int numTargs, ComplexMatrixN u)
This calls swapQubitAmps only when it would involve a distributed communication; if the qubit chunks already fit in the node, it operates the unitary direct.
It is already gauranteed here that all target qubits can fit on each node (this is validated in the front-end)
: refactor so that the 'swap back' isn't performed; instead the qubit locations are updated.
Definition at line 305 of file QuEST_cpu_local.c.
References statevec_multiControlledMultiQubitUnitaryLocal().
 {
     statevec_multiControlledMultiQubitUnitaryLocal(qureg, ctrlMask, targs, numTargs, u);
 }
statevec_multiControlledTwoQubitUnitary()
void statevec_multiControlledTwoQubitUnitary (Qureg qureg, long long int ctrlMask, const int q1, const int q2, ComplexMatrix4 u)
This calls swapQubitAmps only when it would involve a distributed communication; if the qubit chunks already fit in the node, it operates the unitary direct.
Note the order of q1 and q2 in the call to twoQubitUnitaryLocal is important.
: refactor so that the 'swap back' isn't performed; instead the qubit locations are updated. : the double swap (q1,q2 to 0,1) may be possible simultaneously by a bespoke swap routine.
Definition at line 300 of file QuEST_cpu_local.c.
References statevec_multiControlledTwoQubitUnitaryLocal().
 {
     statevec_multiControlledTwoQubitUnitaryLocal(qureg, ctrlMask, q1, q2, u);
 }
statevec_multiControlledUnitary()
void statevec_multiControlledUnitary (Qureg qureg, long long int ctrlQubitsMask, long long int ctrlFlipMask, const int targetQubit, ComplexMatrix2 u)
Definition at line 225 of file QuEST_cpu_local.c.
References statevec_multiControlledUnitaryLocal().
 {
     statevec_multiControlledUnitaryLocal(qureg, targetQubit, ctrlQubitsMask, ctrlFlipMask, u);
 }
statevec_pauliX()
void statevec_pauliX (Qureg qureg, const int targetQubit)
Definition at line 230 of file QuEST_cpu_local.c.
References statevec_pauliXLocal().
 {
     statevec_pauliXLocal(qureg, targetQubit);
 }
statevec_pauliY()
void statevec_pauliY (Qureg qureg, const int targetQubit)
Definition at line 235 of file QuEST_cpu_local.c.
References statevec_pauliYLocal().
 {
     int conjFac = 1;
     statevec_pauliYLocal(qureg, targetQubit, conjFac);
 }
statevec_pauliYConj()
void statevec_pauliYConj (Qureg qureg, const int targetQubit)
Definition at line 241 of file QuEST_cpu_local.c.
References statevec_pauliYLocal().
 {
     int conjFac = -1;
     statevec_pauliYLocal(qureg, targetQubit, conjFac);
 }
statevec_swapQubitAmps()
void statevec_swapQubitAmps (Qureg qureg, int qb1, int qb2)
Definition at line 310 of file QuEST_cpu_local.c.
References statevec_swapQubitAmpsLocal().
 {
     statevec_swapQubitAmpsLocal(qureg, qb1, qb2);
 }
statevec_unitary()
void statevec_unitary (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
Definition at line 210 of file QuEST_cpu_local.c.
References statevec_unitaryLocal().
 {
     statevec_unitaryLocal(qureg, targetQubit, u);
 }
syncQuESTEnv()
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 172 of file QuEST_cpu_local.c.
{
     // MPI Barrier goes here in MPI version.
 }
syncQuESTSuccess()
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
If any one process has a zero successCode all processes will return a zero success code.
Parameters
[in] successCode 1 if process task succeeded, 0 if process task failed
Returns
1 if all processes succeeded, 0 if any one process failed
Definition at line 176 of file QuEST_cpu_local.c.
{
     return successCode;
 }