Quantum Exact Simulation Toolkit: Catch::Matchers::Vector::ApproxMatcher< T > Struct Template Reference
Catch::Matchers::Vector::ApproxMatcher< T > Struct Template Reference abstract
#include <catch.hpp>
Public Member Functions
ApproxMatcher (std::vector< T > const &comparator)
std::string describe () const override
template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
ApproxMatcher & epsilon (T const &newEpsilon)
template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
ApproxMatcher & margin (T const &newMargin)
bool match (std::vector< T > const &v) const override
virtual bool match (T const &arg) const=0
MatchNotOf< T > operator! () const
MatchAllOf< T > operator&& (MatcherBase const &other) const
MatchAnyOf< T > operator|| (MatcherBase const &other) const
template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
ApproxMatcher & scale (T const &newScale)
std::string toString () const
Data Fields
Catch::Detail::Approx approx = Catch::Detail::Approx::custom()
std::vector< T > const & m_comparator
Protected Attributes
std::string m_cachedToString
Detailed Description
template<typename T>
struct Catch::Matchers::Vector::ApproxMatcher< T >
Definition at line 3613 of file catch.hpp.
Constructor & Destructor Documentation
ApproxMatcher()
template<typename T > Catch::Matchers::Vector::ApproxMatcher< T >::ApproxMatcher (std::vector< T > const & comparator) inline
Definition at line 3615 of file catch.hpp.
 : m_comparator( comparator ) {}
Member Function Documentation
describe()
template<typename T > std::string Catch::Matchers::Vector::ApproxMatcher< T >::describe () const inline override virtual
Implements Catch::Matchers::Impl::MatcherUntypedBase.
Definition at line 3625 of file catch.hpp.
{
                 return "is approx: " + ::Catch::Detail::stringify( m_comparator );
             }
References Catch::Detail::stringify().
epsilon()
template<typename T > template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> ApproxMatcher& Catch::Matchers::Vector::ApproxMatcher< T >::epsilon (T const & newEpsilon) inline
Definition at line 3629 of file catch.hpp.
{
                 approx.epsilon(newEpsilon);
                 return *this;
             }
References Catch::Matchers::Vector::ApproxMatcher< T >::epsilon().
Referenced by Catch::Matchers::Vector::ApproxMatcher< T >::epsilon().
margin()
template<typename T > template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> ApproxMatcher& Catch::Matchers::Vector::ApproxMatcher< T >::margin (T const & newMargin) inline
Definition at line 3634 of file catch.hpp.
{
                 approx.margin(newMargin);
                 return *this;
             }
References Catch::Matchers::Vector::ApproxMatcher< T >::margin().
Referenced by Catch::Matchers::Vector::ApproxMatcher< T >::margin().
match() [1/2]
template<typename T > bool Catch::Matchers::Vector::ApproxMatcher< T >::match (std::vector< T > const & v) const inline override
Definition at line 3617 of file catch.hpp.
{
                 if (m_comparator.size() != v.size())
                     return false;
                 for (std::size_t i = 0; i < v.size(); ++i)
                     if (m_comparator[i] != approx(v[i]))
                         return false;
                 return true;
             }
match() [2/2]
virtual bool Catch::Matchers::Impl::MatcherMethod< T >::match (ObjectT const & arg) const pure virtual inherited
Implemented in Catch::Matchers::Generic::PredicateMatcher< T >.
operator!()
template<typename T > MatchNotOf< T > Catch::Matchers::Impl::MatcherBase< T >::operator! inherited
Definition at line 3311 of file catch.hpp.
{
             return MatchNotOf<T>( *this );
         }
operator&&()
template<typename T > MatchAllOf< T > Catch::Matchers::Impl::MatcherBase< T >::operator&& (MatcherBase< T > const & other) const inherited
Definition at line 3303 of file catch.hpp.
{
             return MatchAllOf<T>() && *this && other;
         }
operator||()
template<typename T > MatchAnyOf< T > Catch::Matchers::Impl::MatcherBase< T >::operator|| (MatcherBase< T > const & other) const inherited
Definition at line 3307 of file catch.hpp.
{
             return MatchAnyOf<T>() || *this || other;
         }
scale()
template<typename T > template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> ApproxMatcher& Catch::Matchers::Vector::ApproxMatcher< T >::scale (T const & newScale) inline
Definition at line 3639 of file catch.hpp.
{
                 approx.scale(newScale);
                 return *this;
             }
References Catch::Matchers::Vector::ApproxMatcher< T >::scale().
Referenced by Catch::Matchers::Vector::ApproxMatcher< T >::scale().
toString()
std::string Catch::Matchers::Impl::MatcherUntypedBase::toString () const inherited
Field Documentation
approx
template<typename T > Catch::Detail::Approx Catch::Matchers::Vector::ApproxMatcher< T >::approx = Catch::Detail::Approx::custom() mutable
Definition at line 3645 of file catch.hpp.
m_cachedToString
std::string Catch::Matchers::Impl::MatcherUntypedBase::m_cachedToString mutable protected inherited
Definition at line 3187 of file catch.hpp.
m_comparator
template<typename T > std::vector<T> const& Catch::Matchers::Vector::ApproxMatcher< T >::m_comparator
Definition at line 3644 of file catch.hpp.
The documentation for this struct was generated from the following file:
catch.hpp