Quantum Exact Simulation Toolkit: Catch::IMutableEnumValuesRegistry Struct Reference
Catch::IMutableEnumValuesRegistry Struct Reference abstract
#include <catch.hpp>
Public Member Functions
template<typename E >
Detail::EnumInfo const & registerEnum (StringRef enumName, StringRef allEnums, std::initializer_list< E > values)
virtual Detail::EnumInfo const & registerEnum (StringRef enumName, StringRef allEnums, std::vector< int > const &values)=0
virtual ~IMutableEnumValuesRegistry ()
Detailed Description
Definition at line 1437 of file catch.hpp.
Constructor & Destructor Documentation
~IMutableEnumValuesRegistry()
virtual Catch::IMutableEnumValuesRegistry::~IMutableEnumValuesRegistry () virtual
Member Function Documentation
registerEnum() [1/2]
template<typename E > Detail::EnumInfo const& Catch::IMutableEnumValuesRegistry::registerEnum (StringRef enumName, StringRef allEnums, std::initializer_list< E > values) inline
Definition at line 1443 of file catch.hpp.
{
             static_assert(sizeof(int) >= sizeof(E), "Cannot serialize enum to int");
             std::vector<int> intValues;
             intValues.reserve( values.size() );
             for( auto enumValue : values )
                 intValues.push_back( static_cast<int>( enumValue ) );
             return registerEnum( enumName, allEnums, intValues );
         }
References registerEnum(), and Catch::Generators::values().
registerEnum() [2/2]
virtual Detail::EnumInfo const& Catch::IMutableEnumValuesRegistry::registerEnum (StringRef enumName, StringRef allEnums, std::vector< int > const & values) pure virtual
Referenced by registerEnum().
The documentation for this struct was generated from the following file:
catch.hpp